<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
<OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GeoKernel.LabelHalo.Wpf</RootNamespace>
    <AssemblyName>LabelHalo.Wpf</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <ApplicationIcon>..\Images\GeoKernelAppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\Images\GeoKernelAppIcon.ico" Link="Images\GeoKernelAppIcon.ico" />
  </ItemGroup>
<ItemGroup>
    <PackageReference Include="GeoKernel.NET" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="..\Common\Common.csproj" /></ItemGroup>
</Project>

