<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
<OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GeoKernel.LabelRotation.Winforms</RootNamespace>
    <AssemblyName>LabelRotation.Winforms</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="GeoKernel.NET.WinForms.Controls" Version="$(GeoKernelDotNetPackageVersion)" />
  </ItemGroup>
</Project>

