using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using GeoKernel.Examples.Common;
using GeoKernel.NET.Wpf.Controls;
namespace GeoKernel.RouteOptimization.Wpf;

public sealed class MainWindow : Window
{
    readonly GeoKernelViewerControl viewer = new(); readonly Button reset = new() { Content = "New optimization", IsEnabled = false }, calculate = new() { Content = "Optimize route", IsEnabled = false }; readonly TextBox vehicles = new() { Text = "1", Width = 55 }; readonly ListBox routeList = new(), roadList = new(); readonly TextBlock summary = new() { Text = "Select a depot and at least two visits.", TextWrapping = TextWrapping.Wrap }, status = new(); readonly OverlayWindow overlay; OptimizationEngine? engine; IReadOnlySet<int> component = new HashSet<int>(); readonly List<RoutePoint> points = []; readonly List<int> nodes = []; OptimizationResult? result; bool busy;
    public MainWindow() { Title = "RouteOptimization"; Width = 1200; Height = 760; WindowStartupLocation = WindowStartupLocation.CenterScreen; Icon = BitmapFrame.Create(new Uri("pack://application:,,,/Images/GeoKernelAppIcon.ico")); var root = new DockPanel(); Content = root; var toolbar = new StackPanel { Orientation = Orientation.Horizontal, Height = 34 }; toolbar.Children.Add(reset); toolbar.Children.Add(calculate); var legend = new TextBlock { VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(8, 0, 0, 0) }; legend.Inlines.Add(new Run("●") { Foreground = Brush("#22C55E") }); legend.Inlines.Add(new Run(" Depot   ")); legend.Inlines.Add(new Run("●") { Foreground = Brush("#F59E0B") }); legend.Inlines.Add(new Run(" Visit")); toolbar.Children.Add(legend); DockPanel.SetDock(toolbar, Dock.Top); root.Children.Add(toolbar); DockPanel.SetDock(status, Dock.Bottom); root.Children.Add(status); var panel = new Grid { Width = 320, Margin = new Thickness(10) }; foreach (var h in new[] { 22d, 85d, 30d, 190d, 25d }) panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(h) }); panel.RowDefinitions.Add(new RowDefinition()); Add(panel, new TextBlock { Text = "Service vehicle routes", FontWeight = FontWeights.Bold }, 0); Add(panel, summary, 1); var row = new StackPanel { Orientation = Orientation.Horizontal }; row.Children.Add(new TextBlock { Text = "Service vehicles:", Width = 210, VerticalAlignment = VerticalAlignment.Center }); row.Children.Add(vehicles); Add(panel, row, 2); Add(panel, routeList, 3); Add(panel, new TextBlock { Text = "Road directions", FontWeight = FontWeights.Bold }, 4); Add(panel, roadList, 5); DockPanel.SetDock(panel, Dock.Right); root.Children.Add(panel); root.Children.Add(viewer); overlay = new(viewer); Loaded += LoadSample; LocationChanged += (_, _) => overlay.SyncBounds(); SizeChanged += (_, _) => overlay.SyncBounds(); StateChanged += (_, _) => overlay.SyncBounds(); Closed += (_, _) => overlay.Close(); viewer.VisibleExtentChanged += (_, _) => overlay.Redraw(); viewer.MapMouseUp += MapClicked; reset.Click += (_, _) => Reset(); calculate.Click += async (_, _) => await Optimize(); routeList.SelectionChanged += (_, _) => SelectVehicle(); roadList.SelectionChanged += (_, _) => SelectRoad(); }
    static SolidColorBrush Brush(string x) => new((Color)ColorConverter.ConvertFromString(x)); static void Add(Grid g, UIElement e, int r) { Grid.SetRow(e, r); g.Children.Add(e); }
    int VehicleCount() => int.TryParse(vehicles.Text, out var x) ? Math.Clamp(x, 1, Math.Max(1, points.Count - 1)) : 1;
    async void LoadSample(object s, RoutedEventArgs e) { Mouse.OverrideCursor = Cursors.Wait; status.Text = "Loading Stockholm road network..."; await Task.Yield(); try { viewer.ActiveTool = GeoKernelViewerTool.Pan; var path = SampleData.EnsureWpfSampleFile(new Uri("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm.zip"), "stockholm.zip", "stockholm", "stockholm.shp", this); if (string.IsNullOrEmpty(path) || !viewer.AddLayerFile(path)) return; viewer.SetLayerCoordinateSystemPreset(0, GeoKernelCoordinateSystemPreset.Wgs84); viewer.SetCoordinateSystemPreset(GeoKernelCoordinateSystemPreset.WebMercator); viewer.SetLayerStyle(0, new GeoKernelLayerStyle { LineColor = "#718684", LineWidth = 1 }); if (!viewer.BuildRoutingGraphForLayer(0, 1e-6, true, "maxspeed", "name", "oneway", 50)) throw new InvalidOperationException("Routing graph could not be built."); status.Text = "Preparing routing graph..."; var snap = await Task.Run(() => viewer.GetRoutingGraphSnapshot()) ?? throw new InvalidOperationException("Routing graph is unavailable."); var prepared = await Task.Run(() => { var x = new OptimizationEngine(snap.Nodes.Select(n => new RouteNode(n.Id, new(n.Position.X, n.Position.Y))), snap.Edges.Select(a => new RouteEdge(a.Id, a.FromId, a.ToId, a.Distance, a.SpeedKmh, a.Geometry.Select(p => new RoutePoint(p.X, p.Y)).ToArray(), a.Attributes.TryGetValue("name", out var name) ? name?.ToString() ?? "" : ""))); return (x, x.LargestComponent()); }); engine = prepared.x; component = prepared.Item2; var extent = viewer.GetLayerInfo(0)?.ProjectedExtent; if (extent is not null) viewer.ViewExtent = extent.Value; reset.IsEnabled = true; overlay.Owner = this; overlay.Show(); Reset(); } catch (Exception ex) { MessageBox.Show(this, ex.Message, Title, MessageBoxButton.OK, MessageBoxImage.Error); } finally { Mouse.OverrideCursor = null; } }
    void Reset() { if (busy) return; points.Clear(); nodes.Clear(); result = null; routeList.Items.Clear(); roadList.Items.Clear(); summary.Text = "Select a depot and at least two visits."; vehicles.Text = "1"; calculate.IsEnabled = false; overlay.SetState(points, [], null, 0); viewer.ActiveTool = GeoKernelViewerTool.Route; status.Text = "Click the map to add the depot."; }
    void MapClicked(object? s, GeoKernelMapMouseEventArgs e) { if (busy || engine is null || e.Tool != GeoKernelViewerTool.Route || (e.ButtonOrButtons & 1) == 0) return; var c = nodes.Count == 0 ? component : engine.Reachable(nodes[^1]); var n = engine.Nearest(c, OptimizationEngine.ToWgs(new(e.WorldPoint.X, e.WorldPoint.Y)), 2000); if (n is null) { MessageBox.Show(this, "No reachable road node was found near this point.", Title, MessageBoxButton.OK, MessageBoxImage.Warning); return; } if (nodes.Count > 0 && nodes[^1] == n.Id) return; nodes.Add(n.Id); points.Add(OptimizationEngine.ToWeb(n.Position)); result = null; routeList.Items.Clear(); roadList.Items.Clear(); overlay.SetState(points, [], null, 0); var visits = Math.Max(0, points.Count - 1); summary.Text = $"Depot + {visits} visit(s) selected."; var current = VehicleCount(); vehicles.Text = Math.Min(current, Math.Max(1, visits)).ToString(); calculate.IsEnabled = points.Count >= 3; status.Text = points.Count == 1 ? "Depot selected. Add at least two visit points." : $"Visit {visits} added. Add another visit or optimize."; }
    async Task Optimize() { if (busy || engine is null || nodes.Count < 3) return; var vehicleCount = VehicleCount(); busy = true; calculate.IsEnabled = reset.IsEnabled = false; status.Text = "Optimizing service vehicle routes..."; try { result = await Task.Run(() => engine.Optimize(nodes, vehicleCount)); if (result is null) { MessageBox.Show(this, "The selected visits cannot form connected vehicle routes.", Title, MessageBoxButton.OK, MessageBoxImage.Warning); return; } routeList.Items.Clear(); for (var i = 0; i < result.Vehicles.Count; i++) { var v = result.Vehicles[i]; var labels = string.Join(" → ", v.Order.Select(x => x == 0 ? "D" : x.ToString()).Append("D")); routeList.Items.Add($"Vehicle {i + 1}: {labels}\n{v.Route.Distance / 1000:0.00} km • {v.Route.Time / 60:0.0} min"); } summary.Text = $"{result.Vehicles.Count} vehicles • {points.Count - 1} visits\nFleet distance: {result.TotalDistance / 1000:0.00} km\nLongest route: {result.LongestDistance / 1000:0.00} km\nCombined driving time: {result.TotalTime / 60:0.0} min"; overlay.SetState(points, result.Vehicles.Select(x => x.Route.Geometry).ToArray(), null, 0); routeList.SelectedIndex = 0; status.Text = "Routes optimized for all service vehicles."; } finally { busy = false; reset.IsEnabled = true; calculate.IsEnabled = nodes.Count >= 3; } }
    void SelectVehicle() { if (result is null || routeList.SelectedIndex < 0 || routeList.SelectedIndex >= result.Vehicles.Count) return; var i = routeList.SelectedIndex; overlay.SetState(points, result.Vehicles.Select(x => x.Route.Geometry).ToArray(), result.Vehicles[i].Route.Geometry, i); roadList.Items.Clear(); foreach (var (step, x) in result.Vehicles[i].Steps.Select((x, i) => (x, i))) roadList.Items.Add($"{x + 1}. {step.Name}\n    {(step.Distance >= 1000 ? $"{step.Distance / 1000:0.0} km" : $"{step.Distance:0} m")}"); }
    void SelectRoad() { if (result is null || routeList.SelectedIndex < 0 || roadList.SelectedIndex < 0) return; var s = result.Vehicles[routeList.SelectedIndex].Steps; if (roadList.SelectedIndex < s.Count) overlay.SetHighlight(s[roadList.SelectedIndex].Geometry); }
    sealed class OverlayWindow : Window { readonly GeoKernelViewerControl viewer; readonly Drawing drawing; public OverlayWindow(GeoKernelViewerControl v) { viewer = v; drawing = new(v); Content = drawing; WindowStyle = WindowStyle.None; AllowsTransparency = true; Background = Brushes.Transparent; ShowInTaskbar = false; ResizeMode = ResizeMode.NoResize; Loaded += (_, _) => SyncBounds(); SourceInitialized += (_, _) => { var h = new WindowInteropHelper(this).Handle; SetWindowLong(h, -20, GetWindowLong(h, -20) | 0x20 | 0x08000000 | 0x80); }; } protected override void OnActivated(EventArgs e) { base.OnActivated(e); Owner?.Activate(); } public void SyncBounds() { if (!IsVisible || !viewer.IsVisible) return; var screen = viewer.PointToScreen(new Point()); var source = PresentationSource.FromVisual(viewer); var p = source?.CompositionTarget?.TransformFromDevice.Transform(screen) ?? screen; Left = p.X; Top = p.Y; Width = viewer.ActualWidth; Height = viewer.ActualHeight; Redraw(); } public void SetState(IReadOnlyList<RoutePoint> s, IReadOnlyList<IReadOnlyList<RoutePoint>> r, IReadOnlyList<RoutePoint>? h, int a) => drawing.SetState(s, r, h, a); public void SetHighlight(IReadOnlyList<RoutePoint>? h) => drawing.SetHighlight(h); public void Redraw() => drawing.InvalidateVisual(); [DllImport("user32.dll")] static extern int GetWindowLong(IntPtr h, int i); [DllImport("user32.dll")] static extern int SetWindowLong(IntPtr h, int i, int v); }
    sealed class Drawing : FrameworkElement { readonly GeoKernelViewerControl viewer; IReadOnlyList<RoutePoint> stops = []; IReadOnlyList<IReadOnlyList<RoutePoint>> routes = []; IReadOnlyList<RoutePoint>? highlight; int active; static readonly Brush[] colors = [Brush("#2563EB"), Brush("#F97316"), Brush("#9333EA"), Brush("#0891B2"), Brush("#DB2777"), Brush("#65A30D"), Brush("#CA8A04"), Brush("#4F46E5")]; public Drawing(GeoKernelViewerControl v) { viewer = v; IsHitTestVisible = false; ClipToBounds = true; } public void SetState(IReadOnlyList<RoutePoint> s, IReadOnlyList<IReadOnlyList<RoutePoint>> r, IReadOnlyList<RoutePoint>? h, int a) { stops = s.ToArray(); routes = r; highlight = h; active = a; InvalidateVisual(); } public void SetHighlight(IReadOnlyList<RoutePoint>? h) { highlight = h; InvalidateVisual(); } protected override void OnRender(DrawingContext dc) { for (var i = 0; i < routes.Count; i++) if (i != active) Line(dc, routes[i], colors[i % colors.Length], 3, .53); if (active >= 0 && active < routes.Count) Line(dc, routes[active], colors[active % colors.Length], 5, 1); if (highlight is not null) { Line(dc, highlight, Brush("#FFD60A"), 10, .82); Line(dc, highlight, Brush("#DC2626"), 4, 1); } for (var i = 0; i < stops.Count; i++) Marker(dc, stops[i], i); } void Line(DrawingContext dc, IReadOnlyList<RoutePoint> p, Brush b, double w, double opacity) { var points = p.Select(Screen).Where(x => double.IsFinite(x.X) && double.IsFinite(x.Y)).ToArray(); if (points.Length < 2) return; var g = new StreamGeometry(); using (var c = g.Open()) { c.BeginFigure(points[0], false, false); c.PolyLineTo(points.Skip(1).ToArray(), true, true); } var brush = b.Clone(); brush.Opacity = opacity; dc.DrawGeometry(null, new Pen(brush, w) { StartLineCap = PenLineCap.Round, EndLineCap = PenLineCap.Round, LineJoin = PenLineJoin.Round }, g); } void Marker(DrawingContext dc, RoutePoint p, int i) { var x = Screen(p); dc.DrawEllipse(i == 0 ? Brush("#22C55E") : Brush("#F59E0B"), new Pen(i == 0 ? Brush("#14532D") : Brush("#78350F"), 2), x, 8, 8); var text = new FormattedText(i == 0 ? "D" : i.ToString(), System.Globalization.CultureInfo.CurrentCulture, FlowDirection.LeftToRight, new Typeface("Segoe UI"), 10, Brush("#FFFFFF"), VisualTreeHelper.GetDpi(this).PixelsPerDip); dc.DrawText(text, new Point(x.X - text.Width / 2, x.Y - text.Height / 2)); } Point Screen(RoutePoint p) { var x = viewer.WorldToScreen(p.X, p.Y); return new(x.X, x.Y); } }
}
