namespace GeoKernel.RouteOptimization.Wpf;

internal readonly record struct RoutePoint(double X, double Y); internal sealed record RouteNode(int Id, RoutePoint Position); internal sealed record RouteEdge(int Id, int FromId, int ToId, double Distance, double SpeedKmh, IReadOnlyList<RoutePoint> Geometry, string Name); internal sealed record RouteLeg(IReadOnlyList<int> EdgeIds, IReadOnlyList<RoutePoint> Geometry, double Distance, double Time); internal sealed record RoadStep(string Name, double Distance, IReadOnlyList<RoutePoint> Geometry); internal sealed record VehicleRoute(IReadOnlyList<int> Order, RouteLeg Route, IReadOnlyList<RoadStep> Steps); internal sealed record OptimizationResult(IReadOnlyList<VehicleRoute> Vehicles, double TotalDistance, double TotalTime, double LongestDistance);
internal sealed class OptimizationEngine
{
    const double Earth = 6371008.8, Limit = 20037508.342789244; readonly Dictionary<int, RouteNode> nodes; readonly Dictionary<int, RouteEdge> edges; readonly Dictionary<int, List<RouteEdge>> output; public OptimizationEngine(IEnumerable<RouteNode> n, IEnumerable<RouteEdge> e) { nodes = n.ToDictionary(x => x.Id); edges = e.ToDictionary(x => x.Id); output = edges.Values.GroupBy(x => x.FromId).ToDictionary(x => x.Key, x => x.ToList()); }
    public IReadOnlySet<int> LargestComponent() { var seen = new HashSet<int>(); var largest = new HashSet<int>(); foreach (var seed in nodes.Keys) { if (!seen.Add(seed)) continue; var set = new HashSet<int> { seed }; var q = new Queue<int>(); q.Enqueue(seed); while (q.Count > 0) foreach (var e in output.GetValueOrDefault(q.Dequeue()) ?? []) if (seen.Add(e.ToId)) { set.Add(e.ToId); q.Enqueue(e.ToId); } if (set.Count > largest.Count) largest = set; } return largest; }
    public IReadOnlySet<int> Reachable(int start) { var set = new HashSet<int> { start }; var q = new Queue<int>(); q.Enqueue(start); while (q.Count > 0) foreach (var e in output.GetValueOrDefault(q.Dequeue()) ?? []) if (set.Add(e.ToId)) q.Enqueue(e.ToId); return set; }
    public RouteNode? Nearest(IReadOnlySet<int> c, RoutePoint p, double max) { RouteNode? f = null; var best = max; foreach (var id in c) if (nodes.TryGetValue(id, out var n)) { var d = Geo(p, n.Position); if (d < best) { best = d; f = n; } } return f; }
    Dictionary<int, double> Distances(int s) { var costs = new Dictionary<int, double> { { s, 0 } }; var q = new PriorityQueue<int, double>(); q.Enqueue(s, 0); while (q.TryDequeue(out var n, out var c)) { if (c > costs.GetValueOrDefault(n, double.PositiveInfinity)) continue; foreach (var e in output.GetValueOrDefault(n) ?? []) { var x = c + e.Distance; if (x >= costs.GetValueOrDefault(e.ToId, double.PositiveInfinity)) continue; costs[e.ToId] = x; q.Enqueue(e.ToId, x); } } return costs; }
    RouteLeg? Leg(int s, int f) { var costs = new Dictionary<int, double> { { s, 0 } }; var prev = new Dictionary<int, RouteEdge>(); var q = new PriorityQueue<int, double>(); q.Enqueue(s, 0); while (q.TryDequeue(out var n, out var c)) { if (c > costs.GetValueOrDefault(n, double.PositiveInfinity)) continue; if (n == f) break; foreach (var e in output.GetValueOrDefault(n) ?? []) { var x = c + e.Distance; if (x >= costs.GetValueOrDefault(e.ToId, double.PositiveInfinity)) continue; costs[e.ToId] = x; prev[e.ToId] = e; q.Enqueue(e.ToId, x); } } if (!costs.ContainsKey(f)) return null; var ids = new List<int>(); for (var n = f; n != s;) { if (!prev.TryGetValue(n, out var e)) return null; ids.Add(e.Id); n = e.FromId; } ids.Reverse(); var g = new List<RoutePoint>(); double d = 0, t = 0; foreach (var id in ids) { var e = edges[id]; d += e.Distance; t += e.Distance / ((e.SpeedKmh > 0 ? e.SpeedKmh : 50) * 1000 / 3600); Append(g, e.Geometry.Select(ToWeb)); } return g.Count > 1 ? new(ids, g, d, t) : null; }
    public OptimizationResult? Optimize(IReadOnlyList<int> stops, int vc) { var n = stops.Count; var m = new double[n, n]; for (var i = 0; i < n; i++) { var c = Distances(stops[i]); for (var j = 0; j < n; j++) m[i, j] = c.GetValueOrDefault(stops[j], double.PositiveInfinity); } var o = new List<int> { 0 }; var rem = new HashSet<int>(Enumerable.Range(1, n - 1)); while (rem.Count > 0) { var cur = o[^1]; var b = rem.OrderBy(x => m[cur, x]).First(); if (!double.IsFinite(m[cur, b])) return null; o.Add(b); rem.Remove(b); } double Cost(IReadOnlyList<int> v) { double c = 0; for (var i = 1; i < v.Count; i++) c += m[v[i - 1], v[i]]; return c + m[v[^1], 0]; } for (var imp = true; imp;) { imp = false; var best = Cost(o); for (var a = 1; a < o.Count; a++) for (var b = a + 1; b < o.Count; b++) { var x = o.ToList(); (x[a], x[b]) = (x[b], x[a]); var c = Cost(x); if (c + .01 < best) { o = x; best = c; imp = true; } } } vc = Math.Min(vc, n - 1); var ass = Enumerable.Range(0, vc).Select(_ => new List<int> { 0 }).ToArray(); for (var p = 1; p < o.Count; p++) ass[Math.Min(vc - 1, (p - 1) * vc / (o.Count - 1))].Add(o[p]); var vehicles = new List<VehicleRoute>(); foreach (var a in ass) { var ids = new List<int>(); var g = new List<RoutePoint>(); double d = 0, t = 0; for (var i = 1; i <= a.Count; i++) { var from = a[i - 1]; var to = i == a.Count ? 0 : a[i]; var leg = Leg(stops[from], stops[to]); if (leg is null) return null; ids.AddRange(leg.EdgeIds); Append(g, leg.Geometry); d += leg.Distance; t += leg.Time; } vehicles.Add(new(a, new(ids, g, d, t), Steps(ids))); } return new(vehicles, vehicles.Sum(x => x.Route.Distance), vehicles.Sum(x => x.Route.Time), vehicles.Max(x => x.Route.Distance)); }
    IReadOnlyList<RoadStep> Steps(IEnumerable<int> ids) { var r = new List<RoadStep>(); foreach (var e in ids.Select(id => edges[id])) { var name = string.IsNullOrWhiteSpace(e.Name) ? "Unnamed road" : e.Name.Trim(); var g = e.Geometry.Select(ToWeb).ToArray(); if (r.Count > 0 && string.Equals(r[^1].Name, name, StringComparison.OrdinalIgnoreCase)) { var p = r[^1].Geometry.ToList(); Append(p, g); r[^1] = new(name, r[^1].Distance + e.Distance, p); } else r.Add(new(name, e.Distance, g)); } return r; }
    static void Append(List<RoutePoint> t, IEnumerable<RoutePoint> p) { foreach (var x in p) if (t.Count == 0 || t[^1] != x) t.Add(x); }
    public static RoutePoint ToWgs(RoutePoint p) => new(p.X / Limit * 180, Math.Atan(Math.Exp(p.Y / Limit * Math.PI)) * 360 / Math.PI - 90); public static RoutePoint ToWeb(RoutePoint p) { var l = Math.Clamp(p.Y, -85.05112878, 85.05112878); return new(p.X * Limit / 180, Math.Log(Math.Tan((90 + l) * Math.PI / 360)) * Limit / Math.PI); }
    static double Geo(RoutePoint a, RoutePoint b) { double x = a.Y * Math.PI / 180, y = b.Y * Math.PI / 180, dy = y - x, dx = (b.X - a.X) * Math.PI / 180; var v = Math.Pow(Math.Sin(dy / 2), 2) + Math.Cos(x) * Math.Cos(y) * Math.Pow(Math.Sin(dx / 2), 2); return Earth * 2 * Math.Atan2(Math.Sqrt(v), Math.Sqrt(1 - v)); }
}
