using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using GeoKernel.Examples.Common;
using GeoKernel.NET.Wpf.Controls;

namespace GeoKernel.Isochrone.Wpf;
public sealed class MainWindow : Window
{
    private readonly GeoKernelViewerControl _viewer = new(); private readonly Button _select = new() { Content = "Select isochrone origin", IsEnabled = false }; private readonly TextBlock _summary = new() { Text = "Select an origin point.", TextWrapping = TextWrapping.Wrap }; private readonly ListBox _bands = new(); private readonly TextBlock _status = new(); private readonly OverlayWindow _overlay; private IsochroneEngine? _engine; private IReadOnlySet<int> _component = new HashSet<int>(); private RoutePoint? _origin; private IsochroneResult? _result; private bool _calculating;
    public MainWindow()
    {
        Title = "Isochrone"; Width = 1200; Height = 760; WindowStartupLocation = WindowStartupLocation.CenterScreen; Icon = BitmapFrame.Create(new Uri("pack://application:,,,/Images/GeoKernelAppIcon.ico")); var root = new DockPanel(); Content = root;
        var toolbar = new StackPanel { Orientation = Orientation.Horizontal, Height = 34 }; toolbar.Children.Add(_select); var legend = new TextBlock { VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(8,0,0,0) }; legend.Inlines.Add(new Run("●") { Foreground = Brush("#22C55E") }); legend.Inlines.Add(new Run(" Origin")); toolbar.Children.Add(legend); DockPanel.SetDock(toolbar, Dock.Top); root.Children.Add(toolbar); DockPanel.SetDock(_status, Dock.Bottom); root.Children.Add(_status);
        var panel = new Grid { Width = 310, Margin = new Thickness(10) }; panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(24) }); panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(56) }); panel.RowDefinitions.Add(new RowDefinition()); panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(110) }); Add(panel, new TextBlock { Text = "Travel-time isochrone", FontWeight = FontWeights.Bold }, 0); Add(panel, _summary, 1); Add(panel, _bands, 2); Add(panel, new TextBlock { Text = "Click a band to highlight it.\n\nGreen: 0–5 min\nOrange: 5–10 min\nRed: 10–15 min", TextWrapping = TextWrapping.Wrap }, 3); DockPanel.SetDock(panel, Dock.Right); root.Children.Add(panel); root.Children.Add(_viewer); _overlay = new OverlayWindow(_viewer);
        Loaded += LoadSample; LocationChanged += (_, _) => _overlay.SyncBounds(); SizeChanged += (_, _) => _overlay.SyncBounds(); StateChanged += (_, _) => _overlay.SyncBounds(); Closed += (_, _) => _overlay.Close(); _viewer.VisibleExtentChanged += (_, _) => _overlay.Redraw(); _viewer.MapMouseUp += MapClicked; _select.Click += (_, _) => BeginSelection(); _bands.SelectionChanged += (_, _) => { if (_bands.SelectedIndex >= 0) _overlay.SetState(_origin, _result, _bands.SelectedIndex); };
    }
    private static SolidColorBrush Brush(string value) => new((Color)ColorConverter.ConvertFromString(value)); private static void Add(Grid grid, UIElement element, int row) { Grid.SetRow(element,row); grid.Children.Add(element); }
    private async void LoadSample(object sender, RoutedEventArgs e) { Mouse.OverrideCursor = Cursors.Wait; _status.Text = "Loading Stockholm road network..."; await Task.Yield(); try { _viewer.ActiveTool = GeoKernelViewerTool.Pan; var path = SampleData.EnsureWpfSampleFile(new Uri("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm.zip"), "stockholm.zip", "stockholm", "stockholm.shp", this); if (string.IsNullOrEmpty(path) || !_viewer.AddLayerFile(path)) return; _viewer.SetLayerCoordinateSystemPreset(0, GeoKernelCoordinateSystemPreset.Wgs84); _viewer.SetCoordinateSystemPreset(GeoKernelCoordinateSystemPreset.WebMercator); _viewer.SetLayerStyle(0, new GeoKernelLayerStyle { LineColor = "#718684", LineWidth = 1 }); if (!_viewer.BuildRoutingGraphForLayer(0,1e-6,true,"maxspeed","name","oneway",50)) throw new InvalidOperationException("Routing graph could not be built."); _status.Text = "Preparing routing graph..."; var snapshot = await Task.Run(() => _viewer.GetRoutingGraphSnapshot()) ?? throw new InvalidOperationException("Routing graph is unavailable."); var prepared = await Task.Run(() => { var engine = new IsochroneEngine(snapshot.Nodes.Select(x => new RouteNode(x.Id,new(x.Position.X,x.Position.Y))), snapshot.Edges.Select(x => new RouteEdge(x.Id,x.FromId,x.ToId,x.Distance,x.SpeedKmh,x.Geometry.Select(p => new RoutePoint(p.X,p.Y)).ToArray()))); return (engine,engine.LargestComponent()); }); _engine = prepared.engine; _component = prepared.Item2; var extent = _viewer.GetLayerInfo(0)?.ProjectedExtent; if (extent is not null) _viewer.ViewExtent = extent.Value; _select.IsEnabled = true; _overlay.Owner = this; _overlay.Show(); BeginSelection(); } catch (Exception ex) { MessageBox.Show(this,ex.Message,Title,MessageBoxButton.OK,MessageBoxImage.Error); } finally { Mouse.OverrideCursor = null; } }
    private void BeginSelection() { _origin = null; _result = null; _bands.Items.Clear(); _summary.Text = "Select an origin point."; _overlay.SetState(null,null,-1); _viewer.ActiveTool = GeoKernelViewerTool.Route; _status.Text = "Click the map to choose an isochrone origin."; }
    private async void MapClicked(object? sender, GeoKernelMapMouseEventArgs e) { if (_calculating || _engine is null || e.Tool != GeoKernelViewerTool.Route || (e.ButtonOrButtons & 1) == 0) return; var snap = _engine.Nearest(_component,IsochroneEngine.ToWgs84(new(e.WorldPoint.X,e.WorldPoint.Y)),2000); if (snap is null) { MessageBox.Show(this,"No road node was found near the selected point.",Title,MessageBoxButton.OK,MessageBoxImage.Warning); return; } _calculating = true; _select.IsEnabled = false; _status.Text = "Calculating isochrone..."; _origin = IsochroneEngine.ToWebMercator(snap.Node.Position); _overlay.SetState(_origin,null,-1); try { _result = await Task.Run(() => _engine.Calculate(snap.Node.Id)); _bands.Items.Clear(); var minutes = new[] { 5,10,15 }; for (var i=0;i<3;i++) _bands.Items.Add($"Within {minutes[i]} minutes\n{_result.Bands[i].CumulativeNodes} cumulative nodes • {_result.Bands[i].EdgeCount} band edges"); _summary.Text = $"Origin snap: {snap.Distance:0.0} m\n{_result.Bands[2].CumulativeNodes} nodes reachable within 15 minutes."; _bands.SelectedIndex = 0; _overlay.SetState(_origin,_result,0); _status.Text = "Isochrone calculated successfully."; } finally { _calculating = false; _select.IsEnabled = true; } }
    private sealed class OverlayWindow : Window { private readonly GeoKernelViewerControl _viewer; private readonly Drawing _drawing; public OverlayWindow(GeoKernelViewerControl viewer) { _viewer=viewer; _drawing=new Drawing(viewer); Content=_drawing; WindowStyle=WindowStyle.None; AllowsTransparency=true; Background=Brushes.Transparent; ShowInTaskbar=false; ResizeMode=ResizeMode.NoResize; Loaded+=(_,_)=>SyncBounds(); SourceInitialized += (_,_) => { var h=new WindowInteropHelper(this).Handle; SetWindowLong(h,-20,GetWindowLong(h,-20)|0x20|0x08000000|0x80); }; } protected override void OnActivated(EventArgs e) { base.OnActivated(e); Owner?.Activate(); } public void SyncBounds() { if (!IsVisible || !_viewer.IsVisible || _viewer.ActualWidth<=0 || _viewer.ActualHeight<=0) return; var screen=_viewer.PointToScreen(new Point()); var source=PresentationSource.FromVisual(_viewer); var p=source?.CompositionTarget?.TransformFromDevice.Transform(screen)??screen; Left=p.X; Top=p.Y; Width=_viewer.ActualWidth; Height=_viewer.ActualHeight; Redraw(); } public void SetState(RoutePoint? origin,IsochroneResult? result,int active) => _drawing.SetState(origin,result,active); public void Redraw()=>_drawing.ClearPaths(); [DllImport("user32.dll")] private static extern int GetWindowLong(IntPtr h,int i); [DllImport("user32.dll")] private static extern int SetWindowLong(IntPtr h,int i,int v); }
    private sealed class Drawing : FrameworkElement { private readonly GeoKernelViewerControl _viewer; private readonly StreamGeometry?[] _paths=new StreamGeometry?[3]; private RoutePoint? _origin; private IsochroneResult? _result; private int _active; private static readonly Color[] Colors=[(Color)ColorConverter.ConvertFromString("#16A34A"),(Color)ColorConverter.ConvertFromString("#F59E0B"),(Color)ColorConverter.ConvertFromString("#DC2626")]; public Drawing(GeoKernelViewerControl viewer) { _viewer=viewer; IsHitTestVisible=false; ClipToBounds=true; } public void SetState(RoutePoint? origin,IsochroneResult? result,int active) { if(!ReferenceEquals(_result,result)) Array.Clear(_paths); _origin=origin; _result=result; _active=active; InvalidateVisual(); } public void ClearPaths(){Array.Clear(_paths);InvalidateVisual();} protected override void OnRender(DrawingContext dc) { dc.PushClip(new RectangleGeometry(new Rect(0,0,ActualWidth,ActualHeight))); if (_result is not null) for (var band=2;band>=0;band--) { var color=Colors[band]; color.A=(byte)(band==_active?250:135); dc.DrawGeometry(null,new Pen(new SolidColorBrush(color),band==_active?4.5:2.5){StartLineCap=PenLineCap.Round,EndLineCap=PenLineCap.Round,LineJoin=PenLineJoin.Round},PathFor(band)); } if (_origin is { } o) dc.DrawEllipse(Brush("#22C55E"),new Pen(Brush("#14532D"),2),Screen(o),9,9); dc.Pop(); } private StreamGeometry PathFor(int band){if(_paths[band] is not null)return _paths[band]!;var geometry=new StreamGeometry();using(var c=geometry.Open())if(_result is not null)foreach(var line in _result.Bands[band].Lines){var points=line.Select(Screen).Where(p=>double.IsFinite(p.X)&&double.IsFinite(p.Y)).ToArray();if(points.Length<2)continue;c.BeginFigure(points[0],false,false);c.PolyLineTo(points.Skip(1).ToArray(),true,true);}geometry.Freeze();return _paths[band]=geometry;} private Point Screen(RoutePoint p){var v=_viewer.WorldToScreen(p.X,p.Y);return new(v.X,v.Y);} }
}
