<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget><Prefer32Bit>false</Prefer32Bit>
    <ApplicationIcon>..\Measure.Winforms\resources\geokernel.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="GeoKernel.NET" Version="1.1.28" /><ProjectReference Include="..\Common\Common.csproj" /></ItemGroup>
  <ItemGroup>
    <Resource Include="..\Measure.Winforms\resources\geokernel.ico" Link="Images\GeoKernelAppIcon.ico" />
    <Resource Include="..\Measure.Winforms\resources\pan.png" Link="Images\Pan.png" />
    <Resource Include="..\Measure.Winforms\resources\measure-distance.png" Link="Images\MeasureDistance.png" />
    <Resource Include="..\Measure.Winforms\resources\measure-area.png" Link="Images\MeasureArea.png" />
    <Resource Include="..\Measure.Winforms\resources\delete.png" Link="Images\Delete.png" />
    <Resource Include="..\Measure.Winforms\resources\full-extent.png" Link="Images\FullExtent.png" />
  </ItemGroup>
</Project>
