<Project>
  <PropertyGroup>
    <GeoKernelSamplesRoot>$(MSBuildThisFileDirectory)</GeoKernelSamplesRoot>
    <GeoKernelDotNetPackageVersion>1.0.6</GeoKernelDotNetPackageVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <VcpkgXUseBuiltInApplocalDeps>true</VcpkgXUseBuiltInApplocalDeps>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <BaseOutputPath>$(GeoKernelSamplesRoot)outputs\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(GeoKernelSamplesRoot)intermediates\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
