<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="GeoKernel.NET" Version="*" />
  </ItemGroup>
</Project>
