<Project>
  <ItemDefinitionGroup Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">
    <ClCompile>
      <ProgramDataBaseFileName>$(IntDir)$(MSBuildProjectName).compile.pdb</ProgramDataBaseFileName>
      <AdditionalOptions>/FS %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <Link>
      <ProgramDatabaseFile>$(OutDir)$(MSBuildProjectName).pdb</ProgramDatabaseFile>
    </Link>
  </ItemDefinitionGroup>

  <ItemGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <Compile Remove="$(MSBuildProjectDirectory)\obj\**\*.cs" />
    <EmbeddedResource Remove="$(MSBuildProjectDirectory)\obj\**\*" />
    <None Remove="$(MSBuildProjectDirectory)\obj\**\*" />
  </ItemGroup>

</Project>
