using System.Text.Json;
using System.Windows;
using GeoKernel.Examples.Common;
using GeoKernel.NET.Wpf.Controls;
namespace GeoKernel.RasterTileCache.Wpf;
public sealed partial class MainWindow
{
 private string _path="",_mode="No Raster Loaded";private JsonElement? _benchmark;public MainWindow()=>InitializeComponent();
 private void Window_Loaded(object s,RoutedEventArgs e){viewerControl.ActiveTool=GeoKernelViewerTool.Pan;_path=SampleData.EnsureKnownWpfSampleFile("world_8km.tif",this);if(!string.IsNullOrWhiteSpace(_path))Load(TileCacheMode.Large);}
 private void LoadDisabled_Click(object s,RoutedEventArgs e)=>Load(TileCacheMode.Disabled);private void LoadSmall_Click(object s,RoutedEventArgs e)=>Load(TileCacheMode.Small);private void LoadLarge_Click(object s,RoutedEventArgs e)=>Load(TileCacheMode.Large);private void FullExtent_Click(object s,RoutedEventArgs e)=>viewerControl.FullExtent();private void Benchmark_Click(object s,RoutedEventArgs e)=>Diagnostics(true,false);private void ClearCache_Click(object s,RoutedEventArgs e){Diagnostics(false,true);_benchmark=null;statusText.Text="Memory tile cache cleared.";}
 private void Load(TileCacheMode mode){try{viewerControl.ClearLayers();progressBar.Value=0;_benchmark=null;_mode=mode switch{TileCacheMode.Disabled=>"Cache Disabled",TileCacheMode.Small=>"Small Cache Budget",_=>"Large Cache Budget"};var o=new GeoKernelLayerLoadOptions{PrepareRasterOverviews=true,RasterOverviewMinimumPixels=0,RasterTileCacheEnabled=mode!=TileCacheMode.Disabled};if(mode==TileCacheMode.Small){o.RasterTileCachePixelBudget=128*1024;o.RasterTileCacheMaximumItemPixels=128*1024;}else if(mode==TileCacheMode.Large){o.RasterTileCachePixelBudget=4*1024*1024;o.RasterTileCacheMaximumItemPixels=512*512;}else{o.RasterTileCachePixelBudget=0;o.RasterTileCacheMaximumItemPixels=0;}var p=new Progress<GeoKernelLayerLoadProgress>(x=>{if(x.Progress.HasValue)progressBar.Value=Math.Clamp(x.Progress.Value,0,100);if(!string.IsNullOrWhiteSpace(x.Status))statusText.Text=x.Status;});if(!viewerControl.AddLayerFile(_path,o,p))throw new InvalidOperationException($"Raster could not be loaded:\n{_path}");viewerControl.SetLayerName(0,_mode);viewerControl.FullExtent();progressBar.Value=100;statusText.Text=$"{_mode} loaded.";Diagnostics(false,false);}catch(Exception ex){statusText.Text="Load failed.";MessageBox.Show(this,ex.Message,Title,MessageBoxButton.OK,MessageBoxImage.Error);}}
 private void Diagnostics(bool run,bool clear){if(viewerControl.LayerCount==0){statusText.Text="Load a raster first.";return;}try{if(run)statusText.Text="Running tile cache benchmark...";using var d=JsonDocument.Parse(viewerControl.GetRasterTileCacheDiagnosticsJson(0,run,clear));var r=d.RootElement.Clone();if(r.TryGetProperty("benchmark",out var b))_benchmark=b.Clone();detailsTextBox.Text=Details(r);if(run)statusText.Text=_benchmark is null?"Benchmark failed.":$"Second pass: {G(_benchmark.Value,"secondPassMs")} ms, cache hits={G(_benchmark.Value,"secondPassHits")}.";}catch(Exception ex){MessageBox.Show(this,ex.Message,Title,MessageBoxButton.OK,MessageBoxImage.Error);}}
 private string Details(JsonElement r)=>string.Join(Environment.NewLine,"RasterTileCache sample","",$"Load mode: {_mode}",$"Source: {_path}","","Raster metadata",$"Driver: {G(r,"driverName")}",$"Size: {G(r,"width")} x {G(r,"height")} px",$"Bands: {G(r,"bandCount")}",$"Overview count: {G(r,"overviewCount")}","","Cache stats",$"Enabled: {G(r,"enabled")}",$"Items: {G(r,"itemCount")}",$"Used pixel cost: {G(r,"usedPixelCost")}",$"Max pixel cost: {G(r,"maxPixelCost")}",$"Max item pixel cost: {G(r,"maxItemPixelCost")}","","LayerLoadOptions knobs","RasterTileCacheEnabled","RasterTileCachePixelBudget","RasterTileCacheMaximumItemPixels","",Benchmark());
 private string Benchmark()=>_benchmark is not {ValueKind:JsonValueKind.Object}?"Benchmark has not run.":string.Join(Environment.NewLine,"Benchmark",$"Tiles read per pass: {G(_benchmark.Value,"tileCount")}",$"First pass: {G(_benchmark.Value,"firstPassMs")} ms, cache hits={G(_benchmark.Value,"firstPassHits")}, overview={G(_benchmark.Value,"firstPassOverviewLevel")}",$"Second pass: {G(_benchmark.Value,"secondPassMs")} ms, cache hits={G(_benchmark.Value,"secondPassHits")}, overview={G(_benchmark.Value,"secondPassOverviewLevel")}","","How to read this","- First pass fills the memory tile cache.","- Second pass requests the same tiles again.","- Large budget should retain all tiles; disabled cache should report zero hits.");private static string G(JsonElement e,string n)=>e.TryGetProperty(n,out var v)?v.ToString():"-";private enum TileCacheMode{Disabled,Small,Large}
}
