namespace GeoKernel.LabelRotation.Winforms;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null; private SplitContainer splitContainer; private TableLayoutPanel controlsLayout; private Label titleLabel; private Label rotationLabel; private NumericUpDown rotationNumeric; private Button resetButton; private global::GeoKernel.NET.WinForms.GeoKernelViewerControl geoKernelViewerControl; private StatusStrip statusStrip; private ToolStripStatusLabel statusLabel; private ToolStripProgressBar downloadProgressBar;
    protected override void Dispose(bool disposing) { if (disposing && components is not null) components.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container(); var resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm)); splitContainer = new SplitContainer(); controlsLayout = new TableLayoutPanel(); titleLabel = new Label(); rotationLabel = new Label(); rotationNumeric = new NumericUpDown(); resetButton = new Button(); geoKernelViewerControl = new GeoKernel.NET.WinForms.GeoKernelViewerControl(); statusStrip = new StatusStrip(); statusLabel = new ToolStripStatusLabel(); downloadProgressBar = new ToolStripProgressBar();
        ((System.ComponentModel.ISupportInitialize)splitContainer).BeginInit(); splitContainer.Panel1.SuspendLayout(); splitContainer.Panel2.SuspendLayout(); splitContainer.SuspendLayout(); controlsLayout.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)rotationNumeric).BeginInit(); statusStrip.SuspendLayout(); SuspendLayout();
        splitContainer.Dock = DockStyle.Fill; splitContainer.FixedPanel = FixedPanel.Panel1; splitContainer.Panel1.Controls.Add(controlsLayout); splitContainer.Panel2.Controls.Add(geoKernelViewerControl); splitContainer.SplitterDistance = 240; splitContainer.SplitterWidth = 1;
        controlsLayout.ColumnCount = 1; controlsLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); controlsLayout.Controls.Add(titleLabel, 0, 0); controlsLayout.Controls.Add(rotationLabel, 0, 1); controlsLayout.Controls.Add(rotationNumeric, 0, 2); controlsLayout.Controls.Add(resetButton, 0, 3); controlsLayout.Dock = DockStyle.Fill; controlsLayout.Padding = new Padding(10); controlsLayout.RowCount = 5; controlsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F)); controlsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F)); controlsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F)); controlsLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F)); controlsLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        titleLabel.Dock = DockStyle.Fill; titleLabel.Font = new Font("Segoe UI", 9F, FontStyle.Bold); titleLabel.Text = "Label rotation"; titleLabel.TextAlign = ContentAlignment.MiddleLeft; rotationLabel.Dock = DockStyle.Fill; rotationLabel.Text = "Rotation"; rotationLabel.TextAlign = ContentAlignment.MiddleLeft; rotationNumeric.DecimalPlaces = 1; rotationNumeric.Minimum = -180; rotationNumeric.Maximum = 180; rotationNumeric.Increment = 5; rotationNumeric.Value = 0; rotationNumeric.Enabled = false; rotationNumeric.Dock = DockStyle.Fill; rotationNumeric.ValueChanged += rotationNumeric_ValueChanged; resetButton.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right; resetButton.Height = 30; resetButton.Margin = new Padding(0, 5, 0, 5); resetButton.Text = "Reset Rotation"; resetButton.Enabled = false; resetButton.UseVisualStyleBackColor = true; resetButton.Click += resetButton_Click;
        geoKernelViewerControl.Dock = DockStyle.Fill; geoKernelViewerControl.BackColor = Color.White; statusStrip.Items.AddRange(new ToolStripItem[] { statusLabel, downloadProgressBar }); statusStrip.Dock = DockStyle.Bottom; statusLabel.Spring = true; statusLabel.Text = "Ready"; statusLabel.TextAlign = ContentAlignment.MiddleLeft; downloadProgressBar.Size = new Size(180, 18); downloadProgressBar.Visible = false;
        AutoScaleDimensions = new SizeF(7F, 15F); AutoScaleMode = AutoScaleMode.Font; ClientSize = new Size(1200, 800); Controls.Add(splitContainer); Controls.Add(statusStrip); Icon = (Icon)resources.GetObject("$this.Icon"); Name = "MainForm"; StartPosition = FormStartPosition.CenterScreen; Text = "LabelRotation"; Shown += MainForm_Shown;
        splitContainer.Panel1.ResumeLayout(false); splitContainer.Panel2.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)splitContainer).EndInit(); splitContainer.ResumeLayout(false); controlsLayout.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)rotationNumeric).EndInit(); statusStrip.ResumeLayout(false); statusStrip.PerformLayout(); ResumeLayout(false); PerformLayout();
    }
}
