using System.Text.Json;
using System.IO;
using GeoKernel.Examples.Common;
using GeoKernel.NET.WinForms;

namespace GeoKernel.BuildingSegmentationInference.Winforms;

public sealed class MainForm:Form
{
    static readonly Uri RasterUrl=new("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/buildings.zip");
    static readonly Uri ModelUrl=new("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/buildings-model.zip");
    readonly GeoKernelViewerControl viewer=new(){Dock=DockStyle.Fill}; readonly TextBox modelPath=new(); readonly TextBox rasterPath=new(); readonly TextBox labelPath=new();
    readonly ComboBox provider=new(){DropDownStyle=ComboBoxStyle.DropDownList}; readonly Button run=new(){Text="Run building segmentation inference",Height=30}; readonly ProgressBar progress=new(){Minimum=0,Maximum=100,Height=20};
    readonly Label progressText=new(){AutoSize=true}; readonly TextBox details=new(){Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill}; readonly ToolStripStatusLabel status=new();
    readonly GeoKernelAnalysis analysis=new(); AnalysisLayer? predictionLayer;
    public MainForm()
    {
        Text="BuildingSegmentationInference";Width=1280;Height=850;Icon=new Icon(Path.Combine(AppContext.BaseDirectory,"resources","GeoKernelAppIcon.ico"));
        provider.Items.AddRange(["Auto","CPU","CUDA","DirectML"]);provider.SelectedIndex=0;
        var right=new Panel{Dock=DockStyle.Right,Width=420,Padding=new Padding(10)};var form=new TableLayoutPanel{Dock=DockStyle.Top,Height=300,ColumnCount=2,RowCount=9,AutoSize=false};form.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,105));form.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));
        form.RowStyles.Add(new RowStyle(SizeType.Absolute,24));form.RowStyles.Add(new RowStyle(SizeType.Absolute,38));form.RowStyles.Add(new RowStyle(SizeType.Absolute,34));form.RowStyles.Add(new RowStyle(SizeType.Absolute,34));form.RowStyles.Add(new RowStyle(SizeType.Absolute,34));form.RowStyles.Add(new RowStyle(SizeType.Absolute,30));form.RowStyles.Add(new RowStyle(SizeType.Absolute,32));form.RowStyles.Add(new RowStyle(SizeType.Absolute,22));form.RowStyles.Add(new RowStyle(SizeType.Absolute,22));
        form.Controls.Add(new Label{Text="Building segmentation inference",AutoSize=true,Font=new Font(Font,FontStyle.Bold)},0,0);form.SetColumnSpan(form.GetControlFromPosition(0,0)!,2);form.Controls.Add(new Label{Text="Run a GeoKernel model package on a georeferenced RGB raster.",AutoSize=true},0,1);form.SetColumnSpan(form.GetControlFromPosition(0,1)!,2);
        AddPath(form,2,"Model package",modelPath,BrowseModel);AddPath(form,3,"Input raster",rasterPath,BrowseRaster);AddPath(form,4,"Instance labels",labelPath,BrowseLabel);form.Controls.Add(new Label{Text="Execution provider",AutoSize=true,Anchor=AnchorStyles.Left},0,5);provider.Dock=DockStyle.Fill;form.Controls.Add(provider,1,5);form.Controls.Add(run,0,6);form.SetColumnSpan(run,2);form.Controls.Add(progress,0,7);form.SetColumnSpan(progress,2);form.Controls.Add(progressText,0,8);form.SetColumnSpan(progressText,2);
        var diagnosticsLabel=new Label{Text="Inference diagnostics",Dock=DockStyle.Top,Height=22};var legend=new Label{Text="Building segmentation classes\r\n  Background   🔴 Building",Dock=DockStyle.Bottom,Height=45};right.Controls.Add(details);right.Controls.Add(diagnosticsLabel);right.Controls.Add(form);right.Controls.Add(legend);
        var tools=new ToolStrip{GripStyle=ToolStripGripStyle.Hidden};tools.Items.Add("Zoom In",null,(_,_)=>viewer.ZoomIn());tools.Items.Add("Zoom Out",null,(_,_)=>viewer.ZoomOut());tools.Items.Add("Full Extent",null,(_,_)=>viewer.FullExtent());tools.Items.Add("Zoom Rect",null,(_,_)=>viewer.ActiveTool=GeoKernelViewerTool.ZoomBox);tools.Items.Add("Pan",null,(_,_)=>viewer.ActiveTool=GeoKernelViewerTool.Pan);var bar=new StatusStrip();bar.Items.Add(status);Controls.Add(viewer);Controls.Add(right);Controls.Add(tools);Controls.Add(bar);
        viewer.ActiveTool=GeoKernelViewerTool.Pan;viewer.BusyChanged+=(_,e)=>BeginInvoke(()=>RenderProgress(e.Busy));run.Click+=async(_,_)=>await RunInference();FormClosed+=(_,_)=>predictionLayer?.Dispose();details.Text="Preparing the buildings sample...";Shown+=async(_,_)=>await PrepareSamples();
    }
    async Task PrepareSamples(){run.Enabled=false;try{await Task.Yield();rasterPath.Text=SampleData.EnsureSampleFile(RasterUrl,"buildings.zip","buildings","buildings.tif",this);var manifest=SampleData.EnsureSampleFile(ModelUrl,"buildings-model.zip","buildings-model","geokernel-model.json",this);modelPath.Text=Path.GetDirectoryName(manifest)!;UpdateLabelPath();OpenBaseRaster();details.Text="The buildings raster and ONNX model package are ready. Run inference to add building polygons.";}catch(Exception ex){details.Text="Sample preparation failed:\r\n"+ex.Message;MessageBox.Show(this,ex.Message,Text);}finally{run.Enabled=true;}}
    void OpenBaseRaster(){predictionLayer?.Dispose();predictionLayer=null;viewer.ClearLayers();if(!viewer.AddLayerFile(rasterPath.Text))throw new InvalidOperationException("The buildings input raster could not be opened.");viewer.SetLayerName(0,"Buildings RGB source");viewer.RefreshLayers();viewer.FullExtent();status.Text="Map ready.";}
    void UpdateLabelPath(){if(File.Exists(rasterPath.Text))labelPath.Text=Path.Combine(Path.GetDirectoryName(rasterPath.Text)!,Path.GetFileNameWithoutExtension(rasterPath.Text)+"_building_instances.tif");}
    static void AddPath(TableLayoutPanel p,int row,string label,TextBox box,EventHandler browse){p.Controls.Add(new Label{Text=label,AutoSize=true,Anchor=AnchorStyles.Left},0,row);var h=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=new Padding(0,2,0,2),Padding=new Padding(0)};h.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));h.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,78));h.RowStyles.Add(new RowStyle(SizeType.Percent,100));box.Dock=DockStyle.Fill;box.Margin=new Padding(0,1,4,1);var b=new Button{Text="Browse...",Dock=DockStyle.Fill,Margin=new Padding(0)};b.Click+=browse;h.Controls.Add(box,0,0);h.Controls.Add(b,1,0);p.Controls.Add(h,1,row);}
    void BrowseModel(object? s,EventArgs e){using var d=new FolderBrowserDialog{InitialDirectory=modelPath.Text};if(d.ShowDialog(this)==DialogResult.OK)modelPath.Text=d.SelectedPath;}void BrowseRaster(object? s,EventArgs e){using var d=new OpenFileDialog{Filter="GeoTIFF (*.tif;*.tiff)|*.tif;*.tiff",FileName=rasterPath.Text};if(d.ShowDialog(this)==DialogResult.OK){rasterPath.Text=d.FileName;UpdateLabelPath();OpenBaseRaster();}}void BrowseLabel(object? s,EventArgs e){using var d=new SaveFileDialog{Filter="GeoTIFF (*.tif)|*.tif",FileName=labelPath.Text};if(d.ShowDialog(this)==DialogResult.OK)labelPath.Text=d.FileName;}
    async Task RunInference()
    {
        if(!Directory.Exists(modelPath.Text)||!File.Exists(rasterPath.Text)){MessageBox.Show(this,"Select an existing model package and input raster.",Text);return;}run.Enabled=false;SetProgress(0,"Opening model package...");details.Text="Validating the model package and preparing instance inference...";
        try{var reporter=new Progress<AiInstanceVectorizationProgress>(x=>SetProgress(x.Percent,x.Message));var layer=await analysis.RunAiInstanceVectorizationToMemoryAsync(new(){ModelPackagePath=modelPath.Text,RasterPath=rasterPath.Text,LabelRasterPath=labelPath.Text,Provider=Enum.Parse<AIExecutionProvider>(provider.Text),LayerName="building_predictions",InstanceIdField="instance_id",Connectivity=4},reporter);var diagnostics=layer.Diagnostics;SetProgress(95,"Opening source and prediction overlay...");predictionLayer?.Dispose();predictionLayer=layer;viewer.ClearLayers();if(!viewer.AddLayerFile(rasterPath.Text))throw new InvalidOperationException("The source GeoTIFF could not be opened.");layer.AddTo(viewer);if(!viewer.SetLayerStyle(0,new(){FillColor="#FF3B30",FillOpacity=125,LineColor="#C5160A",LineWidth=1.8}))throw new InvalidOperationException("The prediction layer style could not be applied.");viewer.RefreshLayers();viewer.FullExtent();var count=diagnostics.GetProperty("materializedCount").GetInt64();details.Text=$"GeoKernel AI building segmentation inference\r\n\r\nProvider: {provider.Text}\r\nBuilding polygons: {count}\r\n\r\nInstance labels:\r\n{labelPath.Text}\r\n\r\nVector output: in-memory layer";SetProgress(100,"Inference complete");status.Text=$"Building mask and {count} vector polygons created.";}catch(Exception ex){progress.Value=0;progressText.Text="Inference failed";details.Text="Inference failed:\r\n"+ex.Message;MessageBox.Show(this,ex.Message,Text);}finally{run.Enabled=true;}
    }
    void SetProgress(int value,string text){progress.Style=ProgressBarStyle.Continuous;progress.Value=Math.Clamp(value,0,100);progressText.Text=$"{progress.Value}% — {text}";status.Text=text;}void RenderProgress(bool busy){if(!run.Enabled)return;progress.Style=busy?ProgressBarStyle.Marquee:ProgressBarStyle.Continuous;if(!busy)status.Text="Map ready.";}
}
