namespace GeoKernel.RouteOptimization.Winforms;

internal readonly record struct RoutePoint(double X, double Y); internal sealed record RouteNode(int Id, RoutePoint Position); internal sealed record RouteEdge(int Id, int FromId, int ToId, double Distance, double SpeedKmh, IReadOnlyList<RoutePoint> Geometry, string Name); internal sealed record RouteLeg(IReadOnlyList<int> EdgeIds, IReadOnlyList<RoutePoint> Geometry, double Distance, double Time); internal sealed record RoadStep(string Name, double Distance, IReadOnlyList<RoutePoint> Geometry); internal sealed record VehicleRoute(IReadOnlyList<int> Order, RouteLeg Route, IReadOnlyList<RoadStep> Steps); internal sealed record OptimizationResult(IReadOnlyList<VehicleRoute> Vehicles, double TotalDistance, double TotalTime, double LongestDistance);
internal sealed class OptimizationEngine
{
    const double Earth = 6371008.8, Limit = 20037508.342789244; readonly Dictionary<int, RouteNode> nodes; readonly Dictionary<int, RouteEdge> edges; readonly Dictionary<int, List<RouteEdge>> output;
    public OptimizationEngine(IEnumerable<RouteNode> n, IEnumerable<RouteEdge> e) { nodes = n.ToDictionary(x => x.Id); edges = e.ToDictionary(x => x.Id); output = edges.Values.GroupBy(x => x.FromId).ToDictionary(x => x.Key, x => x.ToList()); }
    public IReadOnlySet<int> LargestComponent() { var seen = new HashSet<int>(); var largest = new HashSet<int>(); foreach (var seed in nodes.Keys) { if (!seen.Add(seed)) continue; var set = new HashSet<int> { seed }; var q = new Queue<int>(); q.Enqueue(seed); while (q.Count > 0) foreach (var e in output.GetValueOrDefault(q.Dequeue()) ?? []) if (seen.Add(e.ToId)) { set.Add(e.ToId); q.Enqueue(e.ToId); } if (set.Count > largest.Count) largest = set; } return largest; }
    public IReadOnlySet<int> Reachable(int start) { var set = new HashSet<int> { start }; var q = new Queue<int>(); q.Enqueue(start); while (q.Count > 0) foreach (var e in output.GetValueOrDefault(q.Dequeue()) ?? []) if (set.Add(e.ToId)) q.Enqueue(e.ToId); return set; }
    public RouteNode? Nearest(IReadOnlySet<int> candidates, RoutePoint p, double max) { RouteNode? found = null; var best = max; foreach (var id in candidates) if (nodes.TryGetValue(id, out var n)) { var d = Geo(p, n.Position); if (d < best) { best = d; found = n; } } return found; }
    Dictionary<int, double> Distances(int start) { var costs = new Dictionary<int, double> { { start, 0 } }; var q = new PriorityQueue<int, double>(); q.Enqueue(start, 0); while (q.TryDequeue(out var node, out var cost)) { if (cost > costs.GetValueOrDefault(node, double.PositiveInfinity)) continue; foreach (var e in output.GetValueOrDefault(node) ?? []) { var candidate = cost + e.Distance; if (candidate >= costs.GetValueOrDefault(e.ToId, double.PositiveInfinity)) continue; costs[e.ToId] = candidate; q.Enqueue(e.ToId, candidate); } } return costs; }
    RouteLeg? Leg(int start, int finish) { var costs = new Dictionary<int, double> { { start, 0 } }; var previous = new Dictionary<int, RouteEdge>(); var q = new PriorityQueue<int, double>(); q.Enqueue(start, 0); while (q.TryDequeue(out var node, out var cost)) { if (cost > costs.GetValueOrDefault(node, double.PositiveInfinity)) continue; if (node == finish) break; foreach (var e in output.GetValueOrDefault(node) ?? []) { var candidate = cost + e.Distance; if (candidate >= costs.GetValueOrDefault(e.ToId, double.PositiveInfinity)) continue; costs[e.ToId] = candidate; previous[e.ToId] = e; q.Enqueue(e.ToId, candidate); } } if (!costs.ContainsKey(finish)) return null; var ids = new List<int>(); for (var n = finish; n != start;) { if (!previous.TryGetValue(n, out var e)) return null; ids.Add(e.Id); n = e.FromId; } ids.Reverse(); var geometry = new List<RoutePoint>(); double distance = 0, time = 0; foreach (var id in ids) { var e = edges[id]; distance += e.Distance; time += e.Distance / ((e.SpeedKmh > 0 ? e.SpeedKmh : 50) * 1000 / 3600); Append(geometry, e.Geometry.Select(ToWeb)); } return geometry.Count > 1 ? new(ids, geometry, distance, time) : null; }
    public OptimizationResult? Optimize(IReadOnlyList<int> stops, int vehicleCount) { var count = stops.Count; var matrix = new double[count, count]; for (var i = 0; i < count; i++) { var costs = Distances(stops[i]); for (var j = 0; j < count; j++) matrix[i, j] = costs.GetValueOrDefault(stops[j], double.PositiveInfinity); } var order = new List<int> { 0 }; var remaining = new HashSet<int>(Enumerable.Range(1, count - 1)); while (remaining.Count > 0) { var current = order[^1]; var best = remaining.OrderBy(x => matrix[current, x]).First(); if (!double.IsFinite(matrix[current, best])) return null; order.Add(best); remaining.Remove(best); } double Cost(IReadOnlyList<int> value) { double c = 0; for (var i = 1; i < value.Count; i++) c += matrix[value[i - 1], value[i]]; return c + matrix[value[^1], 0]; } for (var improved = true; improved;) { improved = false; var best = Cost(order); for (var a = 1; a < order.Count; a++) for (var b = a + 1; b < order.Count; b++) { var candidate = order.ToList(); (candidate[a], candidate[b]) = (candidate[b], candidate[a]); var c = Cost(candidate); if (c + .01 < best) { order = candidate; best = c; improved = true; } } } vehicleCount = Math.Min(vehicleCount, count - 1); var assignments = Enumerable.Range(0, vehicleCount).Select(_ => new List<int> { 0 }).ToArray(); for (var p = 1; p < order.Count; p++) assignments[Math.Min(vehicleCount - 1, (p - 1) * vehicleCount / (order.Count - 1))].Add(order[p]); var vehicles = new List<VehicleRoute>(); foreach (var assignment in assignments) { var allIds = new List<int>(); var geometry = new List<RoutePoint>(); double d = 0, t = 0; for (var i = 1; i <= assignment.Count; i++) { var from = assignment[i - 1]; var to = i == assignment.Count ? 0 : assignment[i]; var leg = Leg(stops[from], stops[to]); if (leg is null) return null; allIds.AddRange(leg.EdgeIds); Append(geometry, leg.Geometry); d += leg.Distance; t += leg.Time; } var combined = new RouteLeg(allIds, geometry, d, t); vehicles.Add(new(assignment, combined, Steps(allIds))); } return new(vehicles, vehicles.Sum(x => x.Route.Distance), vehicles.Sum(x => x.Route.Time), vehicles.Max(x => x.Route.Distance)); }
    IReadOnlyList<RoadStep> Steps(IEnumerable<int> ids) { var result = new List<RoadStep>(); foreach (var e in ids.Select(id => edges[id])) { var name = string.IsNullOrWhiteSpace(e.Name) ? "Unnamed road" : e.Name.Trim(); var geometry = e.Geometry.Select(ToWeb).ToArray(); if (result.Count > 0 && string.Equals(result[^1].Name, name, StringComparison.OrdinalIgnoreCase)) { var p = result[^1].Geometry.ToList(); Append(p, geometry); result[^1] = new(name, result[^1].Distance + e.Distance, p); } else result.Add(new(name, e.Distance, geometry)); } return result; }
    static void Append(List<RoutePoint> target, IEnumerable<RoutePoint> points) { foreach (var p in points) if (target.Count == 0 || target[^1] != p) target.Add(p); }
    public static RoutePoint ToWgs(RoutePoint p) => new(p.X / Limit * 180, Math.Atan(Math.Exp(p.Y / Limit * Math.PI)) * 360 / Math.PI - 90); public static RoutePoint ToWeb(RoutePoint p) { var lat = Math.Clamp(p.Y, -85.05112878, 85.05112878); return new(p.X * Limit / 180, Math.Log(Math.Tan((90 + lat) * Math.PI / 360)) * Limit / Math.PI); }
    static double Geo(RoutePoint a, RoutePoint b) { double x = a.Y * Math.PI / 180, y = b.Y * Math.PI / 180, dy = y - x, dx = (b.X - a.X) * Math.PI / 180; var v = Math.Pow(Math.Sin(dy / 2), 2) + Math.Cos(x) * Math.Cos(y) * Math.Pow(Math.Sin(dx / 2), 2); return Earth * 2 * Math.Atan2(Math.Sqrt(v), Math.Sqrt(1 - v)); }
}
