namespace GeoKernel.LabelCollisionOff.Winforms;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null; private TableLayoutPanel rootLayout; private SplitContainer comparisonSplit; private TableLayoutPanel leftPane; private Label leftTitle; private global::GeoKernel.NET.WinForms.GeoKernelViewerControl collisionOnViewer; private TableLayoutPanel rightPane; private Label rightTitle; private global::GeoKernel.NET.WinForms.GeoKernelViewerControl collisionOffViewer; private StatusStrip statusStrip; private ToolStripStatusLabel statusLabel; private ToolStripProgressBar downloadProgressBar;
    protected override void Dispose(bool disposing) { if (disposing && components is not null) components.Dispose(); base.Dispose(disposing); }
    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container(); var resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm)); rootLayout = new TableLayoutPanel(); comparisonSplit = new SplitContainer(); leftPane = new TableLayoutPanel(); leftTitle = new Label(); collisionOnViewer = new GeoKernel.NET.WinForms.GeoKernelViewerControl(); rightPane = new TableLayoutPanel(); rightTitle = new Label(); collisionOffViewer = new GeoKernel.NET.WinForms.GeoKernelViewerControl(); statusStrip = new StatusStrip(); statusLabel = new ToolStripStatusLabel(); downloadProgressBar = new ToolStripProgressBar();
        rootLayout.SuspendLayout(); ((System.ComponentModel.ISupportInitialize)comparisonSplit).BeginInit(); comparisonSplit.Panel1.SuspendLayout(); comparisonSplit.Panel2.SuspendLayout(); comparisonSplit.SuspendLayout(); leftPane.SuspendLayout(); rightPane.SuspendLayout(); statusStrip.SuspendLayout(); SuspendLayout();
        rootLayout.ColumnCount = 1; rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); rootLayout.Controls.Add(comparisonSplit, 0, 0); rootLayout.Controls.Add(statusStrip, 0, 1); rootLayout.Dock = DockStyle.Fill; rootLayout.RowCount = 2; rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
        comparisonSplit.Dock = DockStyle.Fill; comparisonSplit.Panel1.Controls.Add(leftPane); comparisonSplit.Panel2.Controls.Add(rightPane); comparisonSplit.SplitterDistance = 648; comparisonSplit.SplitterWidth = 4; comparisonSplit.Resize += comparisonSplit_Resize;
        leftPane.ColumnCount = 1; leftPane.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); leftPane.Controls.Add(leftTitle, 0, 0); leftPane.Controls.Add(collisionOnViewer, 0, 1); leftPane.Dock = DockStyle.Fill; leftPane.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F)); leftPane.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); leftTitle.Dock = DockStyle.Fill; leftTitle.BackColor = Color.FromArgb(238,238,238); leftTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold); leftTitle.Padding = new Padding(8,0,0,0); leftTitle.Text = "labelAllowOverlap = false"; leftTitle.TextAlign = ContentAlignment.MiddleLeft; collisionOnViewer.Dock = DockStyle.Fill; collisionOnViewer.BackColor = Color.White;
        rightPane.ColumnCount = 1; rightPane.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); rightPane.Controls.Add(rightTitle, 0, 0); rightPane.Controls.Add(collisionOffViewer, 0, 1); rightPane.Dock = DockStyle.Fill; rightPane.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F)); rightPane.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); rightTitle.Dock = DockStyle.Fill; rightTitle.BackColor = Color.FromArgb(238,238,238); rightTitle.Font = new Font("Segoe UI", 9F, FontStyle.Bold); rightTitle.Padding = new Padding(8,0,0,0); rightTitle.Text = "labelAllowOverlap = true"; rightTitle.TextAlign = ContentAlignment.MiddleLeft; collisionOffViewer.Dock = DockStyle.Fill; collisionOffViewer.BackColor = Color.White;
        statusStrip.Items.AddRange(new ToolStripItem[] { statusLabel, downloadProgressBar }); statusStrip.Dock = DockStyle.Fill; statusStrip.SizingGrip = false; statusLabel.Spring = true; statusLabel.Text = "Preparing world and city sample data..."; statusLabel.TextAlign = ContentAlignment.MiddleLeft; downloadProgressBar.Size = new Size(180,18); downloadProgressBar.Visible = false;
        AutoScaleDimensions = new SizeF(7F,15F); AutoScaleMode = AutoScaleMode.Font; ClientSize = new Size(1300,800); Controls.Add(rootLayout); Icon = (Icon)resources.GetObject("$this.Icon"); Name = "MainForm"; StartPosition = FormStartPosition.CenterScreen; Text = "LabelCollisionOff"; Shown += MainForm_Shown;
        rootLayout.ResumeLayout(false); comparisonSplit.Panel1.ResumeLayout(false); comparisonSplit.Panel2.ResumeLayout(false); ((System.ComponentModel.ISupportInitialize)comparisonSplit).EndInit(); comparisonSplit.ResumeLayout(false); leftPane.ResumeLayout(false); rightPane.ResumeLayout(false); statusStrip.ResumeLayout(false); statusStrip.PerformLayout(); ResumeLayout(false);
    }
}
