using System.IO;
using System.IO.Compression;
using System.Net.Http;
using System.Windows;
using System.Windows.Controls;
using GeoKernel.NET.Wpf;
using GeoKernel.NET.Wpf.Controls;

namespace GeoKernel.ObjectDetectionInference.Wpf;

public sealed class MainWindow : Window
{
    const string ImagesUrl="https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/object_detection_images.zip";
    const string ModelUrl="https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/object_detection_model.zip";
    static readonly (int Id,string Name,string Color)[] Classes=[(1,"airplane","#E53935"),(2,"ship","#1E88E5"),(3,"storage_tank","#FB8C00"),(4,"baseball_diamond","#43A047"),(5,"tennis_court","#8E24AA"),(6,"basketball_court","#D81B60"),(7,"ground_track_field","#00ACC1"),(8,"harbor","#FDD835"),(9,"bridge","#3949AB"),(10,"vehicle","#6D4C41")];
    readonly GeoKernelViewerControl viewer=new(); readonly TextBox modelPath=new(),rasterPath=new(),details=new(){IsReadOnly=true,AcceptsReturn=true,TextWrapping=TextWrapping.Wrap}; readonly ComboBox provider=new(); readonly Button run=new(){Content="Run object detection inference"},previous=new(){Content="Previous image"},next=new(){Content="Next image"}; readonly TextBlock position=new(),stage=new(); readonly ProgressBar progress=new(){Minimum=0,Maximum=100}; readonly GeoKernelAnalysis analysis=new(); readonly List<string> images=[]; AnalysisLayer? detectionLayer; int imageIndex=-1;

    public MainWindow()
    {
        Title="ObjectDetectionInference";Width=1280;Height=850;provider.ItemsSource=new[]{"Auto","CPU","CUDA","DirectML"};provider.SelectedIndex=0;
        var root=new DockPanel();var toolbar=new StackPanel{Orientation=Orientation.Horizontal};foreach(var item in new(string,Action)[]{("Zoom In",()=>viewer.ZoomIn()),("Zoom Out",()=>viewer.ZoomOut()),("Full Extent",()=>viewer.FullExtent()),("Pan",()=>viewer.ActiveTool=GeoKernelViewerTool.Pan)}){var button=new Button{Content=item.Item1,Margin=new Thickness(2)};button.Click+=(_,_)=>item.Item2();toolbar.Children.Add(button);}DockPanel.SetDock(toolbar,Dock.Top);root.Children.Add(toolbar);
        var panel=new StackPanel{Width=430,Margin=new Thickness(10)};DockPanel.SetDock(panel,Dock.Right);panel.Children.Add(new TextBlock{Text="NWPU-VHR-10 object detection",FontWeight=FontWeights.Bold});panel.Children.Add(new TextBlock{Text="Class-labelled bounding boxes in an on-the-fly layer."});AddPath(panel,"Model package",modelPath);AddPath(panel,"Input image",rasterPath);panel.Children.Add(new TextBlock{Text="Execution provider"});panel.Children.Add(provider);var nav=new StackPanel{Orientation=Orientation.Horizontal};nav.Children.Add(previous);nav.Children.Add(position);nav.Children.Add(next);panel.Children.Add(nav);panel.Children.Add(run);panel.Children.Add(progress);panel.Children.Add(stage);panel.Children.Add(new TextBlock{Text="Inference diagnostics",FontWeight=FontWeights.Bold});panel.Children.Add(details);panel.Children.Add(new TextBlock{Text="airplane red · ship blue · tank orange · baseball green\ntennis purple · basketball pink · track cyan\nharbor yellow · bridge indigo · vehicle brown",TextWrapping=TextWrapping.Wrap});root.Children.Add(panel);root.Children.Add(viewer);Content=root;viewer.ActiveTool=GeoKernelViewerTool.Pan;
        run.Click+=async(_,_)=>await RunInference();previous.Click+=(_,_)=>SelectImage(imageIndex-1);next.Click+=(_,_)=>SelectImage(imageIndex+1);Loaded+=async(_,_)=>await PrepareSamples();Closed+=(_,_)=>detectionLayer?.Dispose();details.Text="Preparing sample files...";
    }
    static void AddPath(Panel panel,string label,TextBox box){panel.Children.Add(new TextBlock{Text=label});panel.Children.Add(box);}
    async Task PrepareSamples(){run.IsEnabled=false;try{var root=Path.Combine(AppContext.BaseDirectory,"data");var first=await EnsureSample(ImagesUrl,root,"object-detection-images","1.jpg","images");var manifest=await EnsureSample(ModelUrl,root,"object-detection-model","geokernel-model.json","model");images.AddRange(Directory.GetFiles(Path.GetDirectoryName(first)!,"*.jpg").OrderBy(x=>int.Parse(Path.GetFileNameWithoutExtension(x))));EnsurePixelWorldFiles(images);modelPath.Text=Path.GetDirectoryName(manifest)!;SelectImage(0);details.Text=$"{images.Count} images and the ONNX model are ready.";SetProgress(0,"Ready");}catch(Exception ex){details.Text=ex.Message;MessageBox.Show(this,ex.Message,Title);}finally{run.IsEnabled=true;}}
    async Task<string> EnsureSample(string url,string root,string folder,string required,string label){var dir=Path.Combine(root,folder);var target=Path.Combine(dir,required);if(File.Exists(target))return target;Directory.CreateDirectory(dir);var zip=Path.Combine(root,folder+".zip");using var client=new HttpClient();using var response=await client.GetAsync(url,HttpCompletionOption.ResponseHeadersRead);response.EnsureSuccessStatusCode();var total=response.Content.Headers.ContentLength;await using(var input=await response.Content.ReadAsStreamAsync())await using(var output=File.Create(zip)){var buffer=new byte[128*1024];long received=0;int read;while((read=await input.ReadAsync(buffer))>0){await output.WriteAsync(buffer.AsMemory(0,read));received+=read;if(total>0)SetProgress((int)(received*100/total),$"Downloading {label}...");}}SetProgress(100,$"Extracting {label}...");ZipFile.ExtractToDirectory(zip,dir,true);File.Delete(zip);return File.Exists(target)?target:throw new FileNotFoundException(required);}
    static void EnsurePixelWorldFiles(IEnumerable<string> files){const string world="1\r\n0\r\n0\r\n-1\r\n0.5\r\n-0.5\r\n";foreach(var image in files){var sidecar=Path.ChangeExtension(image,".jgw");if(!File.Exists(sidecar))File.WriteAllText(sidecar,world);}}
    void SelectImage(int index){if(index<0||index>=images.Count)return;imageIndex=index;rasterPath.Text=images[index];position.Text=$" {index+1} / {images.Count} — {Path.GetFileName(images[index])} ";previous.IsEnabled=index>0;next.IsEnabled=index+1<images.Count;OpenSource();}
    void OpenSource(){detectionLayer?.Dispose();detectionLayer=null;viewer.ClearLayers();if(!viewer.AddLayerFile(rasterPath.Text))throw new InvalidOperationException("Source image could not be opened.");viewer.FullExtent();}
    async Task RunInference(){run.IsEnabled=false;SetProgress(0,"Running tiled object detection...");try{var layer=await analysis.RunAiObjectDetectionToMemoryAsync(new(){ModelPackagePath=modelPath.Text,RasterPath=rasterPath.Text,Provider=Enum.Parse<AIExecutionProvider>(provider.SelectedItem!.ToString()!),LayerName="object_detections",WindowSize=512,Overlap=256,NmsThreshold=0.3},new Progress<AiObjectDetectionProgress>(x=>SetProgress(x.Percent,x.Message)));var result=layer.Diagnostics;var count=result.GetProperty("materializedCount").GetInt64();var tiles=$"{result.GetProperty("tilesProcessed").GetInt32()} ({result.GetProperty("tilesX").GetInt32()} x {result.GetProperty("tilesY").GetInt32()})";detectionLayer?.Dispose();detectionLayer=null;viewer.ClearLayers();viewer.AddLayerFile(rasterPath.Text);if(count>0){detectionLayer=layer;layer.AddTo(viewer);var baseStyle=DetectionStyle("#FF4020");viewer.SetLayerStyle(0,baseStyle);viewer.SetLayerCategorizedRenderer(0,"class_id",Classes.Select(x=>new GeoKernelCategorizedSymbolClass{Value=x.Id,Label=x.Name,Style=DetectionStyle(x.Color)}),baseStyle);}else layer.Dispose();viewer.RefreshLayers();viewer.FullExtent();details.Text=$"GeoKernel AI tiled object detection\n\nProvider: {provider.SelectedItem}\nWindow: 512, overlap: 256, NMS: 0.3\nTiles processed: {tiles}\nDetections: {count}\nVector output: {(count>0?"in-memory layer":"no detections")}";SetProgress(100,count>0?"Inference complete":"Inference complete — no detections");}catch(Exception ex){details.Text="Inference failed:\n"+ex.Message;MessageBox.Show(this,ex.Message,Title);}finally{run.IsEnabled=true;}}
    static GeoKernelLayerStyle DetectionStyle(string color)=>new(){FillColor=color,FillOpacity=90,LineColor=color,LineWidth=1.5,ShowLabels=true,LabelField="label",LabelFontSize=11,LabelColor="#FFFFFF",LabelHaloEnabled=true,LabelHaloColor="#202020",LabelHaloWidth=2,LabelAllowOverlap=true};
    void SetProgress(int value,string text){progress.Value=Math.Clamp(value,0,100);stage.Text=$"{progress.Value}% — {text}";}
}
