<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><Nullable>enable</Nullable><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings><PlatformTarget>x64</PlatformTarget><AssemblyName>CloudGeoParquetLoad</AssemblyName><ApplicationIcon>..\Images\GeoKernelAppIcon.ico</ApplicationIcon></PropertyGroup>
  <ItemGroup><PackageReference Include="GeoKernel.NET" VersionOverride="1.3.9" /></ItemGroup>
  <ItemGroup><Resource Include="..\Images\GeoKernelAppIcon.ico"><Link>Images\GeoKernelAppIcon.ico</Link></Resource></ItemGroup>
</Project>
