using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using GeoKernel.Examples.Common;
using GeoKernel.NET.Wpf.Controls;

namespace GeoKernel.MultiStopRoute.Wpf;

public sealed class MainWindow : Window
{
    private readonly GeoKernelViewerControl _viewer = new(); private readonly ListBox _legs = new(), _roads = new(); private readonly TextBlock _summary = new() { Text = "Add at least two stops.", TextWrapping = TextWrapping.Wrap }, _status = new(); private readonly Button _reset = new() { Content = "New multi-stop route", IsEnabled = false }, _calculate = new() { Content = "Calculate route", IsEnabled = false }; private readonly OverlayWindow _overlay;
    private MultiStopRoutingEngine? _engine; private IReadOnlySet<int> _mainComponent = new HashSet<int>(); private readonly List<RoutePoint> _stops = []; private readonly List<int> _stopNodes = []; private IReadOnlyList<RouteLeg> _routeLegs = []; private IReadOnlyList<RoadStep> _roadSteps = [];
    public MainWindow()
    {
        Title = "MultiStopRoute"; Width = 1200; Height = 760; WindowStartupLocation = WindowStartupLocation.CenterScreen; Icon = BitmapFrame.Create(new Uri("pack://application:,,,/Images/GeoKernelAppIcon.ico")); var root = new DockPanel(); Content = root;
        var toolbar = new StackPanel { Orientation = Orientation.Horizontal, Height = 34 }; toolbar.Children.Add(_reset); toolbar.Children.Add(_calculate); var legend = new TextBlock { VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(8, 0, 0, 0) }; legend.Inlines.Add(new Run("●") { Foreground = Brush("#22C55E") }); legend.Inlines.Add(new Run(" Start   ")); legend.Inlines.Add(new Run("●") { Foreground = Brush("#F59E0B") }); legend.Inlines.Add(new Run(" Stop   ")); legend.Inlines.Add(new Run("●") { Foreground = Brush("#EF4444") }); legend.Inlines.Add(new Run(" Finish")); toolbar.Children.Add(legend); DockPanel.SetDock(toolbar, Dock.Top); root.Children.Add(toolbar); DockPanel.SetDock(_status, Dock.Bottom); root.Children.Add(_status);
        var panel = new Grid { Width = 320, Margin = new Thickness(10) }; panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(22) }); panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(55) }); panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(190) }); panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(26) }); panel.RowDefinitions.Add(new RowDefinition()); Add(panel, new TextBlock { Text = "Multi-stop route", FontWeight = FontWeights.Bold }, 0); Add(panel, _summary, 1); Add(panel, _legs, 2); Add(panel, new TextBlock { Text = "Road directions", FontWeight = FontWeights.Bold, VerticalAlignment = VerticalAlignment.Bottom }, 3); Add(panel, _roads, 4); DockPanel.SetDock(panel, Dock.Right); root.Children.Add(panel); root.Children.Add(_viewer); _overlay = new OverlayWindow(_viewer);
        Loaded += LoadSample; LocationChanged += (_, _) => _overlay.SyncBounds(); SizeChanged += (_, _) => _overlay.SyncBounds(); StateChanged += (_, _) => _overlay.SyncBounds(); Closed += (_, _) => _overlay.Close(); _viewer.VisibleExtentChanged += (_, _) => _overlay.Redraw(); _viewer.MapMouseUp += MapClicked; _reset.Click += (_, _) => ResetRoute(); _calculate.Click += (_, _) => Calculate(); _legs.SelectionChanged += (_, _) => HighlightLeg(); _roads.SelectionChanged += (_, _) => HighlightRoad();
    }
    private static SolidColorBrush Brush(string value) => new((Color)ColorConverter.ConvertFromString(value)); private static void Add(Grid grid, UIElement element, int row) { Grid.SetRow(element, row); grid.Children.Add(element); }
    private async void LoadSample(object sender, RoutedEventArgs e)
    {
        Mouse.OverrideCursor = Cursors.Wait; _status.Text = "Loading Stockholm road network..."; await Task.Yield();
        try { _viewer.ActiveTool = GeoKernelViewerTool.Pan; var path = SampleData.EnsureWpfSampleFile(new Uri("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm.zip"), "stockholm.zip", "stockholm", "stockholm.shp", this); if (string.IsNullOrEmpty(path) || !_viewer.AddLayerFile(path)) return; _viewer.SetLayerCoordinateSystemPreset(0, GeoKernelCoordinateSystemPreset.Wgs84); _viewer.SetCoordinateSystemPreset(GeoKernelCoordinateSystemPreset.WebMercator); _viewer.SetLayerStyle(0, new GeoKernelLayerStyle { LineColor = "#718684", LineWidth = 1 }); if (!_viewer.BuildRoutingGraphForLayer(0, 1e-6, true, "maxspeed", "name", "oneway", 50)) throw new InvalidOperationException("Routing graph could not be built."); _status.Text = "Preparing routing graph..."; var snapshot = await Task.Run(() => _viewer.GetRoutingGraphSnapshot()) ?? throw new InvalidOperationException("Routing graph is unavailable."); var prepared = await Task.Run(() => { var engine = new MultiStopRoutingEngine(snapshot.Nodes.Select(x => new RouteNode(x.Id, new RoutePoint(x.Position.X, x.Position.Y))), snapshot.Edges.Select(x => new RouteEdge(x.Id, x.FromId, x.ToId, x.Distance, x.SpeedKmh, x.Geometry.Select(p => new RoutePoint(p.X, p.Y)).ToArray(), x.Attributes.TryGetValue("name", out var name) ? name?.ToString() ?? "" : ""))); return (engine, engine.LargestComponent()); }); _engine = prepared.engine; _mainComponent = prepared.Item2; if (_mainComponent.Count == 0) throw new InvalidOperationException("The main connected road network could not be identified."); var extent = _viewer.GetLayerInfo(0)?.ProjectedExtent; if (extent is not null) _viewer.ViewExtent = extent.Value; _reset.IsEnabled = true; _overlay.Owner = this; _overlay.Show(); ResetRoute(); }
        catch (Exception ex) { MessageBox.Show(this, ex.Message, Title, MessageBoxButton.OK, MessageBoxImage.Error); } finally { Mouse.OverrideCursor = null; }
    }
    private void ResetRoute() { _stops.Clear(); _stopNodes.Clear(); _routeLegs = []; _roadSteps = []; _legs.Items.Clear(); _roads.Items.Clear(); _summary.Text = "Add at least two stops."; _calculate.IsEnabled = false; _overlay.SetState(_stops, _routeLegs, null); _viewer.ActiveTool = GeoKernelViewerTool.Route; _status.Text = "Click the map to add the start point."; }
    private void MapClicked(object? sender, GeoKernelMapMouseEventArgs e)
    {
        if (_engine is null || e.Tool != GeoKernelViewerTool.Route || (e.ButtonOrButtons & 1) == 0) return; var candidates = _stopNodes.Count == 0 ? _mainComponent : _engine.Reachable(_stopNodes[^1]); var source = MultiStopRoutingEngine.ToWgs84(new RoutePoint(e.WorldPoint.X, e.WorldPoint.Y)); var node = _engine.Nearest(candidates, source, 2000); if (node is null) { MessageBox.Show(this, "No reachable road node was found near this point.", Title, MessageBoxButton.OK, MessageBoxImage.Warning); return; } if (_stopNodes.Count > 0 && _stopNodes[^1] == node.Id) return; _stopNodes.Add(node.Id); _stops.Add(MultiStopRoutingEngine.ToWebMercator(node.Position)); _routeLegs = []; _roadSteps = []; _legs.Items.Clear(); _roads.Items.Clear(); _summary.Text = $"{_stops.Count} stop(s) selected."; _calculate.IsEnabled = _stops.Count >= 2; _overlay.SetState(_stops, [], null); _status.Text = $"Stop {_stops.Count} added. Add another stop or calculate the route.";
    }
    private void Calculate()
    {
        if (_engine is null || _stopNodes.Count < 2) return; var legs = new List<RouteLeg>(); for (var i = 1; i < _stopNodes.Count; i++) { var leg = _engine.FindLeg(_stopNodes[i - 1], _stopNodes[i]); if (leg is null) { MessageBox.Show(this, $"No route was found for leg {i}.", Title, MessageBoxButton.OK, MessageBoxImage.Warning); return; } legs.Add(leg); } _routeLegs = legs; _roadSteps = _engine.Steps(legs); _legs.Items.Clear(); for (var i = 0; i < legs.Count; i++) _legs.Items.Add($"{i + 1} → {i + 2}   {legs[i].Distance / 1000:0.00} km • {legs[i].Time / 60:0.0} min"); _roads.Items.Clear(); for (var i = 0; i < _roadSteps.Count; i++) _roads.Items.Add($"{i + 1}. {_roadSteps[i].Name}\n    {(_roadSteps[i].Distance >= 1000 ? $"{_roadSteps[i].Distance / 1000:0.0} km" : $"{_roadSteps[i].Distance:0} m")}"); _summary.Text = $"{_stops.Count} stops\n{legs.Sum(x => x.Distance) / 1000:0.00} km  •  {legs.Sum(x => x.Time) / 60:0.0} min"; _overlay.SetState(_stops, legs, null); _status.Text = "Multi-stop route calculated successfully.";
    }
    private void HighlightLeg() => _overlay.SetHighlight(_legs.SelectedIndex >= 0 && _legs.SelectedIndex < _routeLegs.Count ? _routeLegs[_legs.SelectedIndex].Geometry : null); private void HighlightRoad() => _overlay.SetHighlight(_roads.SelectedIndex >= 0 && _roads.SelectedIndex < _roadSteps.Count ? _roadSteps[_roads.SelectedIndex].Geometry : null);
    private sealed class OverlayWindow : Window
    {
        private readonly GeoKernelViewerControl _viewer; private readonly Drawing _drawing;
        public OverlayWindow(GeoKernelViewerControl viewer) { _viewer = viewer; _drawing = new Drawing(viewer); Content = _drawing; WindowStyle = WindowStyle.None; AllowsTransparency = true; Background = Brushes.Transparent; ShowInTaskbar = false; ResizeMode = ResizeMode.NoResize; SourceInitialized += (_, _) => { var h = new WindowInteropHelper(this).Handle; SetWindowLong(h, -20, GetWindowLong(h, -20) | 0x20 | 0x08000000 | 0x80); }; } protected override void OnActivated(EventArgs e) { base.OnActivated(e); Owner?.Activate(); }
        public void SyncBounds() { if (!IsVisible || !_viewer.IsVisible) return; var p = _viewer.PointToScreen(new Point()); Left = p.X; Top = p.Y; Width = _viewer.ActualWidth; Height = _viewer.ActualHeight; Redraw(); } public void SetState(IReadOnlyList<RoutePoint> stops, IReadOnlyList<RouteLeg> legs, IReadOnlyList<RoutePoint>? highlight) { _drawing.SetState(stops, legs, highlight); SyncBounds(); } public void SetHighlight(IReadOnlyList<RoutePoint>? value) => _drawing.SetHighlight(value); public void Redraw() => _drawing.InvalidateVisual(); [DllImport("user32.dll")] private static extern int GetWindowLong(IntPtr h, int i); [DllImport("user32.dll")] private static extern int SetWindowLong(IntPtr h, int i, int v);
    }
    private sealed class Drawing : FrameworkElement
    {
        private readonly GeoKernelViewerControl _viewer; private IReadOnlyList<RoutePoint> _stops = []; private IReadOnlyList<RouteLeg> _legs = []; private IReadOnlyList<RoutePoint>? _highlight;
        public Drawing(GeoKernelViewerControl viewer) { _viewer = viewer; IsHitTestVisible = false; } public void SetState(IReadOnlyList<RoutePoint> stops, IReadOnlyList<RouteLeg> legs, IReadOnlyList<RoutePoint>? highlight) { _stops = stops.ToArray(); _legs = legs; _highlight = highlight; InvalidateVisual(); } public void SetHighlight(IReadOnlyList<RoutePoint>? value) { _highlight = value; InvalidateVisual(); }
        protected override void OnRender(DrawingContext dc) { DrawLine(dc, _legs.SelectMany(x => x.Geometry).ToArray(), Brush("#2563EB"), 5); if (_highlight is not null) { DrawLine(dc, _highlight, new SolidColorBrush(Color.FromArgb(210, 255, 214, 10)), 10); DrawLine(dc, _highlight, Brush("#DC2626"), 4); } for (var i = 0; i < _stops.Count; i++) DrawMarker(dc, _stops[i], i, _stops.Count); }
        private void DrawLine(DrawingContext dc, IReadOnlyList<RoutePoint> points, Brush brush, double width) { if (points.Count < 2) return; var geometry = new StreamGeometry(); using (var c = geometry.Open()) { c.BeginFigure(Screen(points[0]), false, false); c.PolyLineTo(points.Skip(1).Select(Screen).ToArray(), true, true); } dc.DrawGeometry(null, new Pen(brush, width) { StartLineCap = PenLineCap.Round, EndLineCap = PenLineCap.Round, LineJoin = PenLineJoin.Round }, geometry); }
        private void DrawMarker(DrawingContext dc, RoutePoint point, int index, int count) { var fill = Brush(index == 0 ? "#22C55E" : index == count - 1 ? "#EF4444" : "#F59E0B"); var outline = Brush(index == 0 ? "#14532D" : index == count - 1 ? "#7F1D1D" : "#78350F"); var p = Screen(point); dc.DrawEllipse(fill, new Pen(outline, 2), p, 8, 8); var text = new FormattedText((index + 1).ToString(), System.Globalization.CultureInfo.CurrentCulture, FlowDirection.LeftToRight, new Typeface("Segoe UI"), 10, Brushes.White, VisualTreeHelper.GetDpi(this).PixelsPerDip); dc.DrawText(text, new Point(p.X - text.Width / 2, p.Y - text.Height / 2)); } private Point Screen(RoutePoint p) { var v = _viewer.WorldToScreen(p.X, p.Y); return new Point(v.X, v.Y); }
    }
}
