<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="GeoKernel.NET.Wpf.Controls" Version="$(GeoKernelDotNetPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\images\FullExtent.png" Link="Images\FullExtent.png" />
    <Resource Include="..\..\images\Polygon.png" Link="Images\Polygon.png" />
    <Resource Include="..\..\images\Pan.png" Link="Images\Pan.png" />
    <Resource Include="..\..\images\Delete.png" Link="Images\Delete.png" />
  </ItemGroup>
<ItemGroup>
    <Resource Include="..\..\images\GeoKernelAppIcon.ico" Link="Images\GeoKernelAppIcon.ico" />
  </ItemGroup>
</Project>

