using System.Drawing.Drawing2D;
using GeoKernel.Examples.Common;
using GeoKernel.NET.WinForms;

namespace GeoKernel.MultiStopRoute.Winforms;

public sealed class MainForm : Form
{
    private readonly GeoKernelViewerControl _viewer = new() { Dock = DockStyle.Fill }; private readonly ListBox _legs = new() { Dock = DockStyle.Fill }, _roads = new() { Dock = DockStyle.Fill };
    private readonly Label _summary = new() { Dock = DockStyle.Fill, Text = "Add at least two stops." }; private readonly Button _reset = new() { Text = "New multi-stop route", AutoSize = true, Enabled = false }, _calculate = new() { Text = "Calculate route", AutoSize = true, Enabled = false }; private readonly ToolStripStatusLabel _status = new(); private readonly Overlay _overlay;
    private MultiStopRoutingEngine? _engine; private IReadOnlySet<int> _mainComponent = new HashSet<int>(); private readonly List<RoutePoint> _stops = []; private readonly List<int> _stopNodes = []; private IReadOnlyList<RouteLeg> _routeLegs = []; private IReadOnlyList<RoadStep> _roadSteps = [];
    public MainForm()
    {
        Text = "MultiStopRoute"; Width = 1200; Height = 760; StartPosition = FormStartPosition.CenterScreen; var icon = Path.Combine(AppContext.BaseDirectory, "resources", "GeoKernelAppIcon.ico"); if (File.Exists(icon)) Icon = new Icon(icon);
        var toolbar = new FlowLayoutPanel { Dock = DockStyle.Top, Height = 34, WrapContents = false }; toolbar.Controls.Add(_reset); toolbar.Controls.Add(_calculate); AddLegend(toolbar, "Start", Color.FromArgb(34, 197, 94)); AddLegend(toolbar, "Stop", Color.FromArgb(245, 158, 11)); AddLegend(toolbar, "Finish", Color.FromArgb(239, 68, 68));
        var panel = new TableLayoutPanel { Dock = DockStyle.Right, Width = 320, Padding = new Padding(10), RowCount = 6 }; panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 22)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 55)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 190)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 26)); panel.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 0));
        panel.Controls.Add(new Label { Text = "Multi-stop route", Font = new Font(Font, FontStyle.Bold), Dock = DockStyle.Fill }, 0, 0); panel.Controls.Add(_summary, 0, 1); panel.Controls.Add(_legs, 0, 2); panel.Controls.Add(new Label { Text = "Road directions", Font = new Font(Font, FontStyle.Bold), Dock = DockStyle.Fill }, 0, 3); panel.Controls.Add(_roads, 0, 4);
        var status = new StatusStrip(); status.Items.Add(_status); Controls.Add(_viewer); Controls.Add(panel); Controls.Add(toolbar); Controls.Add(status); _overlay = new Overlay(_viewer);
        Shown += LoadSample; Move += (_, _) => _overlay.SyncBounds(); Resize += (_, _) => _overlay.SyncBounds(); FormClosed += (_, _) => _overlay.Close(); _viewer.VisibleExtentChanged += (_, _) => _overlay.Invalidate(); _viewer.MapMouseUp += MapClicked; _reset.Click += (_, _) => ResetRoute(); _calculate.Click += (_, _) => Calculate(); _legs.SelectedIndexChanged += (_, _) => HighlightLeg(); _roads.SelectedIndexChanged += (_, _) => HighlightRoad();
    }
    private static void AddLegend(Control parent, string text, Color color) { parent.Controls.Add(new Label { Text = "●", ForeColor = color, AutoSize = true, Padding = new Padding(8, 7, 0, 0) }); parent.Controls.Add(new Label { Text = text, AutoSize = true, Padding = new Padding(0, 7, 0, 0) }); }
    private async void LoadSample(object? sender, EventArgs e)
    {
        UseWaitCursor = true; _status.Text = "Loading Stockholm road network..."; await Task.Yield();
        try { _viewer.ActiveTool = GeoKernelViewerTool.Pan; var path = SampleData.EnsureSampleFile(new Uri("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm.zip"), "stockholm.zip", "stockholm", "stockholm.shp", this); if (string.IsNullOrEmpty(path) || !_viewer.AddLayerFile(path)) return; _viewer.SetLayerCoordinateSystemPreset(0, GeoKernelCoordinateSystemPreset.Wgs84); _viewer.SetCoordinateSystemPreset(GeoKernelCoordinateSystemPreset.WebMercator); _viewer.SetLayerStyle(0, new GeoKernelLayerStyle { LineColor = "#718684", LineWidth = 1 }); if (!_viewer.BuildRoutingGraphForLayer(0, 1e-6, true, "maxspeed", "name", "oneway", 50)) throw new InvalidOperationException("Routing graph could not be built."); _status.Text = "Preparing routing graph..."; var snapshot = await Task.Run(() => _viewer.GetRoutingGraphSnapshot()) ?? throw new InvalidOperationException("Routing graph is unavailable."); var prepared = await Task.Run(() => { var engine = new MultiStopRoutingEngine(snapshot.Nodes.Select(x => new RouteNode(x.Id, new RoutePoint(x.Position.X, x.Position.Y))), snapshot.Edges.Select(x => new RouteEdge(x.Id, x.FromId, x.ToId, x.Distance, x.SpeedKmh, x.Geometry.Select(p => new RoutePoint(p.X, p.Y)).ToArray(), x.Attributes.TryGetValue("name", out var name) ? name?.ToString() ?? "" : ""))); return (engine, engine.LargestComponent()); }); _engine = prepared.engine; _mainComponent = prepared.Item2; if (_mainComponent.Count == 0) throw new InvalidOperationException("The main connected road network could not be identified."); var extent = _viewer.GetLayerInfo(0)?.ProjectedExtent; if (extent is not null) _viewer.ViewExtent = extent.Value; _reset.Enabled = true; _overlay.Show(this); ResetRoute(); }
        catch (Exception ex) { MessageBox.Show(this, ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Error); } finally { UseWaitCursor = false; }
    }
    private void ResetRoute() { _stops.Clear(); _stopNodes.Clear(); _routeLegs = []; _roadSteps = []; _legs.Items.Clear(); _roads.Items.Clear(); _summary.Text = "Add at least two stops."; _calculate.Enabled = false; _overlay.SetState(_stops, _routeLegs, null); _viewer.ActiveTool = GeoKernelViewerTool.Route; _status.Text = "Click the map to add the start point."; }
    private void MapClicked(object? sender, GeoKernelMapMouseEventArgs e)
    {
        if (_engine is null || e.Tool != GeoKernelViewerTool.Route || (e.ButtonOrButtons & 1) == 0) return; var candidates = _stopNodes.Count == 0 ? _mainComponent : _engine.Reachable(_stopNodes[^1]); var source = MultiStopRoutingEngine.ToWgs84(new RoutePoint(e.WorldPoint.X, e.WorldPoint.Y)); var node = _engine.Nearest(candidates, source, 2000); if (node is null) { MessageBox.Show(this, "No reachable road node was found near this point.", Text, MessageBoxButtons.OK, MessageBoxIcon.Warning); return; } if (_stopNodes.Count > 0 && _stopNodes[^1] == node.Id) return;
        _stopNodes.Add(node.Id); _stops.Add(MultiStopRoutingEngine.ToWebMercator(node.Position)); _routeLegs = []; _roadSteps = []; _legs.Items.Clear(); _roads.Items.Clear(); _summary.Text = $"{_stops.Count} stop(s) selected."; _calculate.Enabled = _stops.Count >= 2; _overlay.SetState(_stops, [], null); _status.Text = $"Stop {_stops.Count} added. Add another stop or calculate the route.";
    }
    private void Calculate()
    {
        if (_engine is null || _stopNodes.Count < 2) return; var legs = new List<RouteLeg>(); for (var i = 1; i < _stopNodes.Count; i++) { var leg = _engine.FindLeg(_stopNodes[i - 1], _stopNodes[i]); if (leg is null) { MessageBox.Show(this, $"No route was found for leg {i}.", Text, MessageBoxButtons.OK, MessageBoxIcon.Warning); return; } legs.Add(leg); }
        _routeLegs = legs; _roadSteps = _engine.Steps(legs); _legs.Items.Clear(); for (var i = 0; i < legs.Count; i++) _legs.Items.Add($"{i + 1} → {i + 2}   {legs[i].Distance / 1000:0.00} km • {legs[i].Time / 60:0.0} min"); _roads.Items.Clear(); for (var i = 0; i < _roadSteps.Count; i++) _roads.Items.Add($"{i + 1}. {_roadSteps[i].Name}\r\n    {(_roadSteps[i].Distance >= 1000 ? $"{_roadSteps[i].Distance / 1000:0.0} km" : $"{_roadSteps[i].Distance:0} m")}"); var distance = legs.Sum(x => x.Distance); var time = legs.Sum(x => x.Time); _summary.Text = $"{_stops.Count} stops\r\n{distance / 1000:0.00} km  •  {time / 60:0.0} min"; _overlay.SetState(_stops, legs, null); _status.Text = "Multi-stop route calculated successfully.";
    }
    private void HighlightLeg() => _overlay.SetHighlight(_legs.SelectedIndex >= 0 && _legs.SelectedIndex < _routeLegs.Count ? _routeLegs[_legs.SelectedIndex].Geometry : null);
    private void HighlightRoad() => _overlay.SetHighlight(_roads.SelectedIndex >= 0 && _roads.SelectedIndex < _roadSteps.Count ? _roadSteps[_roads.SelectedIndex].Geometry : null);
    private sealed class Overlay : Form
    {
        private readonly GeoKernelViewerControl _viewer; private IReadOnlyList<RoutePoint> _stops = []; private IReadOnlyList<RouteLeg> _legs = []; private IReadOnlyList<RoutePoint>? _highlight;
        public Overlay(GeoKernelViewerControl viewer) { _viewer = viewer; FormBorderStyle = FormBorderStyle.None; ShowInTaskbar = false; BackColor = Color.Fuchsia; TransparencyKey = Color.Fuchsia; StartPosition = FormStartPosition.Manual; } protected override bool ShowWithoutActivation => true; protected override CreateParams CreateParams { get { var p = base.CreateParams; p.ExStyle |= 0x08000020 | 0x80; return p; } }
        public void SyncBounds() { if (!Visible || !_viewer.IsHandleCreated) return; Bounds = new Rectangle(_viewer.PointToScreen(Point.Empty), _viewer.ClientSize); Invalidate(); } public void SetState(IReadOnlyList<RoutePoint> stops, IReadOnlyList<RouteLeg> legs, IReadOnlyList<RoutePoint>? highlight) { _stops = stops.ToArray(); _legs = legs; _highlight = highlight; SyncBounds(); Invalidate(); } public void SetHighlight(IReadOnlyList<RoutePoint>? value) { _highlight = value; Invalidate(); } protected override void OnShown(EventArgs e) { base.OnShown(e); SyncBounds(); }
        protected override void OnPaint(PaintEventArgs e) { e.Graphics.SmoothingMode = SmoothingMode.AntiAlias; DrawLine(e.Graphics, _legs.SelectMany(x => x.Geometry).ToArray(), Color.FromArgb(37, 99, 235), 5); if (_highlight is not null) { DrawLine(e.Graphics, _highlight, Color.FromArgb(210, 255, 214, 10), 10); DrawLine(e.Graphics, _highlight, Color.FromArgb(220, 38, 38), 4); } for (var i = 0; i < _stops.Count; i++) DrawMarker(e.Graphics, _stops[i], i, _stops.Count); }
        private void DrawLine(Graphics g, IReadOnlyList<RoutePoint> points, Color color, float width) { if (points.Count < 2) return; using var pen = new Pen(color, width) { StartCap = LineCap.Round, EndCap = LineCap.Round, LineJoin = LineJoin.Round }; g.DrawLines(pen, points.Select(Screen).ToArray()); }
        private void DrawMarker(Graphics g, RoutePoint point, int index, int count) { var p = Screen(point); var fill = index == 0 ? Color.FromArgb(34, 197, 94) : index == count - 1 ? Color.FromArgb(239, 68, 68) : Color.FromArgb(245, 158, 11); var outline = index == 0 ? Color.FromArgb(20, 83, 45) : index == count - 1 ? Color.FromArgb(127, 29, 29) : Color.FromArgb(120, 53, 15); using var brush = new SolidBrush(fill); using var pen = new Pen(outline, 2); g.FillEllipse(brush, p.X - 8, p.Y - 8, 16, 16); g.DrawEllipse(pen, p.X - 8, p.Y - 8, 16, 16); TextRenderer.DrawText(g, (index + 1).ToString(), SystemFonts.DefaultFont, new Rectangle((int)p.X - 8, (int)p.Y - 8, 16, 16), Color.White, TextFormatFlags.HorizontalCenter | TextFormatFlags.VerticalCenter); }
        private PointF Screen(RoutePoint p) { var value = _viewer.WorldToScreen(p.X, p.Y); return new PointF((float)value.X, (float)value.Y); }
    }
}
