namespace GeoKernel.MultiStopRoute.Winforms;

internal readonly record struct RoutePoint(double X, double Y);
internal sealed record RouteNode(int Id, RoutePoint Position);
internal sealed record RouteEdge(int Id, int FromId, int ToId, double Distance, double SpeedKmh, IReadOnlyList<RoutePoint> Geometry, string Name);
internal sealed record RouteLeg(IReadOnlyList<int> EdgeIds, IReadOnlyList<RoutePoint> Geometry, double Distance, double Time);
internal sealed record RoadStep(string Name, double Distance, IReadOnlyList<RoutePoint> Geometry);

internal sealed class MultiStopRoutingEngine
{
    private const double EarthRadius = 6371008.8; private const double MercatorLimit = 20037508.342789244;
    private readonly Dictionary<int, RouteNode> _nodes; private readonly Dictionary<int, RouteEdge> _edges; private readonly Dictionary<int, List<RouteEdge>> _out;
    public MultiStopRoutingEngine(IEnumerable<RouteNode> nodes, IEnumerable<RouteEdge> edges) { _nodes = nodes.ToDictionary(x => x.Id); _edges = edges.ToDictionary(x => x.Id); _out = _edges.Values.GroupBy(x => x.FromId).ToDictionary(x => x.Key, x => x.ToList()); }
    public IReadOnlySet<int> LargestComponent() { var visited = new HashSet<int>(); var largest = new HashSet<int>(); foreach (var seed in _nodes.Keys) { if (!visited.Add(seed)) continue; var set = new HashSet<int> { seed }; var queue = new Queue<int>(); queue.Enqueue(seed); while (queue.Count > 0) { var node = queue.Dequeue(); foreach (var edge in _out.GetValueOrDefault(node) ?? []) if (visited.Add(edge.ToId)) { set.Add(edge.ToId); queue.Enqueue(edge.ToId); } } if (set.Count > largest.Count) largest = set; } return largest; }
    public IReadOnlySet<int> Reachable(int start) { var set = new HashSet<int> { start }; var queue = new Queue<int>(); queue.Enqueue(start); while (queue.Count > 0) foreach (var edge in _out.GetValueOrDefault(queue.Dequeue()) ?? []) if (set.Add(edge.ToId)) queue.Enqueue(edge.ToId); return set; }
    public RouteNode? Nearest(IReadOnlySet<int> candidates, RoutePoint point, double maximum) { RouteNode? result = null; var best = maximum; foreach (var id in candidates) if (_nodes.TryGetValue(id, out var node)) { var value = Distance(point, node.Position); if (value < best) { best = value; result = node; } } return result; }
    public RouteLeg? FindLeg(int start, int finish) { var costs = new Dictionary<int, double> { [start] = 0 }; var previous = new Dictionary<int, RouteEdge>(); var queue = new PriorityQueue<int, double>(); queue.Enqueue(start, 0); while (queue.TryDequeue(out var node, out var cost)) { if (cost > costs.GetValueOrDefault(node, double.PositiveInfinity)) continue; if (node == finish) break; foreach (var edge in _out.GetValueOrDefault(node) ?? []) { var candidate = cost + edge.Distance; if (candidate >= costs.GetValueOrDefault(edge.ToId, double.PositiveInfinity)) continue; costs[edge.ToId] = candidate; previous[edge.ToId] = edge; queue.Enqueue(edge.ToId, candidate); } } if (!costs.ContainsKey(finish)) return null; var ids = new List<int>(); for (var node = finish; node != start;) { if (!previous.TryGetValue(node, out var edge)) return null; ids.Add(edge.Id); node = edge.FromId; } ids.Reverse(); var geometry = new List<RoutePoint>(); double distance = 0, time = 0; foreach (var id in ids) { var edge = _edges[id]; distance += edge.Distance; if (edge.SpeedKmh > 0) time += edge.Distance / (edge.SpeedKmh * 1000 / 3600); Append(geometry, edge.Geometry.Select(ToWebMercator)); } return geometry.Count > 1 ? new RouteLeg(ids, geometry, distance, time) : null; }
    public IReadOnlyList<RoadStep> Steps(IEnumerable<RouteLeg> legs) { var result = new List<RoadStep>(); foreach (var edge in legs.SelectMany(x => x.EdgeIds).Select(id => _edges[id])) { var name = string.IsNullOrWhiteSpace(edge.Name) ? "Unnamed road" : edge.Name.Trim(); var geometry = edge.Geometry.Select(ToWebMercator).ToArray(); if (result.Count > 0 && string.Equals(result[^1].Name, name, StringComparison.OrdinalIgnoreCase)) { var points = result[^1].Geometry.ToList(); Append(points, geometry); result[^1] = new RoadStep(result[^1].Name, result[^1].Distance + edge.Distance, points); } else result.Add(new RoadStep(name, edge.Distance, geometry)); } return result; }
    private static void Append(List<RoutePoint> target, IEnumerable<RoutePoint> points) { foreach (var point in points) if (target.Count == 0 || target[^1] != point) target.Add(point); }
    public static RoutePoint ToWgs84(RoutePoint p) { var longitude = p.X / MercatorLimit * 180; var latitude = Math.Atan(Math.Exp(p.Y / MercatorLimit * Math.PI)) * 360 / Math.PI - 90; return new(longitude, latitude); }
    public static RoutePoint ToWebMercator(RoutePoint p) { var latitude = Math.Clamp(p.Y, -85.05112878, 85.05112878); return new(p.X * MercatorLimit / 180, Math.Log(Math.Tan((90 + latitude) * Math.PI / 360)) * MercatorLimit / Math.PI); }
    private static double Distance(RoutePoint a, RoutePoint b) { var lat1 = a.Y * Math.PI / 180; var lat2 = b.Y * Math.PI / 180; var dlat = lat2 - lat1; var dlon = (b.X - a.X) * Math.PI / 180; var value = Math.Pow(Math.Sin(dlat / 2), 2) + Math.Cos(lat1) * Math.Cos(lat2) * Math.Pow(Math.Sin(dlon / 2), 2); return EarthRadius * 2 * Math.Atan2(Math.Sqrt(value), Math.Sqrt(1 - value)); }
}
