using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using GeoKernel.Examples.Common;
using GeoKernel.NET.Wpf.Controls;

namespace GeoKernel.RouteAnimation.Wpf;
public sealed class MainWindow : Window
{
    private readonly GeoKernelViewerControl _viewer = new(); private readonly ListBox _directions = new(); private readonly TextBlock _summary = new() { Text = "Select a start and finish point.", TextWrapping = TextWrapping.Wrap }, _animationStatus = new() { Text = "Animation is waiting for a route.", TextWrapping = TextWrapping.Wrap }, _status = new(); private readonly Button _select = new() { Content = "Select route points", IsEnabled = false }, _play = new() { Content = "Play", IsEnabled = false }, _pause = new() { Content = "Pause", IsEnabled = false }, _resetAnimation = new() { Content = "Reset", IsEnabled = false }; private readonly DispatcherTimer _timer = new() { Interval = TimeSpan.FromMilliseconds(33) }; private readonly OverlayWindow _overlay;
    private AnimationRoutingEngine? _engine; private IReadOnlySet<int> _mainComponent = new HashSet<int>(); private RoutePoint? _start, _finish; private int _startNode = -1; private AnimationRoute? _route; private double _progress, _duration = 5000;
    public MainWindow()
    {
        Title = "RouteAnimation"; Width = 1200; Height = 760; WindowStartupLocation = WindowStartupLocation.CenterScreen; Icon = BitmapFrame.Create(new Uri("pack://application:,,,/Images/GeoKernelAppIcon.ico")); var root = new DockPanel(); Content = root; var toolbar = new StackPanel { Orientation = Orientation.Horizontal, Height = 34 }; toolbar.Children.Add(_select); var legend = new TextBlock { VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(8, 0, 0, 0) }; legend.Inlines.Add(new Run("●") { Foreground = Brush("#22C55E") }); legend.Inlines.Add(new Run(" Start   ")); legend.Inlines.Add(new Run("●") { Foreground = Brush("#EF4444") }); legend.Inlines.Add(new Run(" Finish")); toolbar.Children.Add(legend); DockPanel.SetDock(toolbar, Dock.Top); root.Children.Add(toolbar); DockPanel.SetDock(_status, Dock.Bottom); root.Children.Add(_status);
        var panel = new Grid { Width = 300, Margin = new Thickness(10) }; panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(22) }); panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(50) }); panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(55) }); panel.RowDefinitions.Add(new RowDefinition { Height = new GridLength(36) }); panel.RowDefinitions.Add(new RowDefinition()); Add(panel, new TextBlock { Text = "Route directions", FontWeight = FontWeights.Bold }, 0); Add(panel, _summary, 1); Add(panel, _animationStatus, 2); var buttons = new StackPanel { Orientation = Orientation.Horizontal }; buttons.Children.Add(_play); buttons.Children.Add(_pause); buttons.Children.Add(_resetAnimation); Add(panel, buttons, 3); Add(panel, _directions, 4); DockPanel.SetDock(panel, Dock.Right); root.Children.Add(panel); root.Children.Add(_viewer); _overlay = new OverlayWindow(_viewer);
        Loaded += LoadSample; LocationChanged += (_, _) => _overlay.SyncBounds(); SizeChanged += (_, _) => _overlay.SyncBounds(); StateChanged += (_, _) => _overlay.SyncBounds(); Closed += (_, _) => _overlay.Close(); _viewer.VisibleExtentChanged += (_, _) => _overlay.Redraw(); _viewer.MapMouseUp += MapClicked; _select.Click += (_, _) => BeginSelection(); _play.Click += (_, _) => Play(); _pause.Click += (_, _) => Pause(); _resetAnimation.Click += (_, _) => ResetAnimation(); _timer.Tick += (_, _) => TickAnimation();
    }
    private static SolidColorBrush Brush(string value) => new((Color)ColorConverter.ConvertFromString(value)); private static void Add(Grid g, UIElement e, int row) { Grid.SetRow(e, row); g.Children.Add(e); }
    private async void LoadSample(object sender, RoutedEventArgs e)
    {
        Mouse.OverrideCursor = Cursors.Wait; _status.Text = "Loading Stockholm road network..."; await Task.Yield();
        try { _viewer.ActiveTool = GeoKernelViewerTool.Pan; var path = SampleData.EnsureWpfSampleFile(new Uri("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm.zip"), "stockholm.zip", "stockholm", "stockholm.shp", this); if (string.IsNullOrEmpty(path) || !_viewer.AddLayerFile(path)) return; _viewer.SetLayerCoordinateSystemPreset(0, GeoKernelCoordinateSystemPreset.Wgs84); _viewer.SetCoordinateSystemPreset(GeoKernelCoordinateSystemPreset.WebMercator); _viewer.SetLayerStyle(0, new GeoKernelLayerStyle { LineColor = "#718684", LineWidth = 1 }); if (!_viewer.BuildRoutingGraphForLayer(0, 1e-6, true, "maxspeed", "name", "oneway", 50)) throw new InvalidOperationException("Routing graph could not be built."); _status.Text = "Preparing routing graph..."; var snapshot = await Task.Run(() => _viewer.GetRoutingGraphSnapshot()) ?? throw new InvalidOperationException("Routing graph is unavailable."); var prepared = await Task.Run(() => { var engine = new AnimationRoutingEngine(snapshot.Nodes.Select(x => new RouteNode(x.Id, new(x.Position.X, x.Position.Y))), snapshot.Edges.Select(x => new RouteEdge(x.Id, x.FromId, x.ToId, x.Distance, x.SpeedKmh, x.Geometry.Select(p => new RoutePoint(p.X, p.Y)).ToArray(), x.Attributes.TryGetValue("name", out var name) ? name?.ToString() ?? "" : ""))); return (engine, engine.LargestComponent()); }); _engine = prepared.engine; _mainComponent = prepared.Item2; if (_mainComponent.Count == 0) throw new InvalidOperationException("The main connected road network could not be identified."); var extent = _viewer.GetLayerInfo(0)?.ProjectedExtent; if (extent is not null) _viewer.ViewExtent = extent.Value; _select.IsEnabled = true; _overlay.Owner = this; _overlay.Show(); BeginSelection(); }
        catch (Exception ex) { MessageBox.Show(this, ex.Message, Title, MessageBoxButton.OK, MessageBoxImage.Error); } finally { Mouse.OverrideCursor = null; }
    }
    private void DisableAnimation() { _timer.Stop(); _progress = 0; _play.IsEnabled = _pause.IsEnabled = _resetAnimation.IsEnabled = false; _animationStatus.Text = "Animation is waiting for a route."; }
    private void BeginSelection() { DisableAnimation(); _start = _finish = null; _startNode = -1; _route = null; _directions.Items.Clear(); _summary.Text = "Select a start and finish point."; _overlay.SetState(null, null, null, -1); _viewer.ActiveTool = GeoKernelViewerTool.Route; _status.Text = "Click the map to choose the start point."; }
    private void MapClicked(object? sender, GeoKernelMapMouseEventArgs e)
    {
        if (_engine is null || e.Tool != GeoKernelViewerTool.Route || (e.ButtonOrButtons & 1) == 0) return; var candidates = _start.HasValue && !_finish.HasValue ? _engine.Reachable(_startNode) : _mainComponent; var node = _engine.Nearest(candidates, AnimationRoutingEngine.ToWgs84(new(e.WorldPoint.X, e.WorldPoint.Y)), 2000); if (node is null) { MessageBox.Show(this, "No road node was found near the selected point.", Title, MessageBoxButton.OK, MessageBoxImage.Warning); return; } var world = AnimationRoutingEngine.ToWebMercator(node.Position);
        if (!_start.HasValue || _finish.HasValue) { DisableAnimation(); _start = world; _finish = null; _startNode = node.Id; _route = null; _directions.Items.Clear(); _summary.Text = "Select the finish point."; _overlay.SetState(_start, null, null, -1); _status.Text = "Start selected. Click the map to choose the finish point."; return; }
        _finish = world; _route = _engine.FindRoute(_startNode, node.Id); if (_route is null) { _overlay.SetState(_start, _finish, null, -1); MessageBox.Show(this, "No connected route was found.", Title, MessageBoxButton.OK, MessageBoxImage.Warning); _status.Text = "No connected route found. Click once to choose a new start."; return; } _progress = 0; _duration = Math.Clamp(_route.Time / 60 * 1000, 5000, 45000); _overlay.SetState(_start, _finish, _route, 0); _play.IsEnabled = _resetAnimation.IsEnabled = true; _pause.IsEnabled = false; _animationStatus.Text = $"Ready: {_route.Distance / 1000:0.00} km • {_route.Time / 60:0.0} min\nAnimation speed adapts to route length."; _summary.Text = $"{_route.Distance / 1000:0.00} km  •  {_route.Time / 60:0.0} min"; _directions.Items.Clear(); var steps = _engine.Steps(_route); for (var i = 0; i < steps.Count; i++) _directions.Items.Add($"{i + 1}. {steps[i].Name}\n    {(steps[i].Distance >= 1000 ? $"{steps[i].Distance / 1000:0.0} km" : $"{steps[i].Distance:0} m")}"); if (steps.Count == 0) _directions.Items.Add("Route has no named road segments."); _status.Text = $"Route: {_route.Distance / 1000:0.00} km, {_route.Time / 60:0.0} min";
    }
    private void Play() { if (_route is null) return; if (_progress >= 1) { _progress = 0; _overlay.SetProgress(0); } _timer.Start(); _play.IsEnabled = false; _pause.IsEnabled = true; } private void Pause() { _timer.Stop(); _play.IsEnabled = true; _pause.IsEnabled = false; } private void ResetAnimation() { if (_route is null) return; _timer.Stop(); _progress = 0; _overlay.SetProgress(0); _animationStatus.Text = $"Ready: {_route.Distance / 1000:0.00} km • {_route.Time / 60:0.0} min"; _play.IsEnabled = true; _pause.IsEnabled = false; }
    private void TickAnimation() { if (_route is null) return; _progress = Math.Min(1, _progress + _timer.Interval.TotalMilliseconds / _duration); _overlay.SetProgress(_progress); _animationStatus.Text = $"Progress: {_progress * 100:0}%\nRemaining: {_route.Distance * (1 - _progress) / 1000:0.00} km • {_route.Time * (1 - _progress) / 60:0.0} min"; if (_progress >= 1) { _timer.Stop(); _pause.IsEnabled = false; _animationStatus.Text = "Destination reached."; } }
    private sealed class OverlayWindow : Window
    {
        private readonly GeoKernelViewerControl _viewer; private readonly Drawing _drawing; public OverlayWindow(GeoKernelViewerControl viewer) { _viewer = viewer; _drawing = new Drawing(viewer); Content = _drawing; WindowStyle = WindowStyle.None; AllowsTransparency = true; Background = Brushes.Transparent; ShowInTaskbar = false; ResizeMode = ResizeMode.NoResize; SourceInitialized += (_, _) => { var h = new WindowInteropHelper(this).Handle; SetWindowLong(h, -20, GetWindowLong(h, -20) | 0x20 | 0x08000000 | 0x80); }; } protected override void OnActivated(EventArgs e) { base.OnActivated(e); Owner?.Activate(); } public void SyncBounds() { if (!IsVisible || !_viewer.IsVisible) return; var p = _viewer.PointToScreen(new Point()); Left = p.X; Top = p.Y; Width = _viewer.ActualWidth; Height = _viewer.ActualHeight; Redraw(); } public void SetState(RoutePoint? start, RoutePoint? finish, AnimationRoute? route, double progress) { _drawing.SetState(start, finish, route, progress); SyncBounds(); } public void SetProgress(double value) => _drawing.SetProgress(value); public void Redraw() => _drawing.InvalidateVisual(); [DllImport("user32.dll")] private static extern int GetWindowLong(IntPtr h, int i); [DllImport("user32.dll")] private static extern int SetWindowLong(IntPtr h, int i, int v);
    }
    private sealed class Drawing : FrameworkElement
    {
        private readonly GeoKernelViewerControl _viewer; private RoutePoint? _start, _finish; private AnimationRoute? _route; private double _progress = -1; public Drawing(GeoKernelViewerControl viewer) { _viewer = viewer; IsHitTestVisible = false; } public void SetState(RoutePoint? start, RoutePoint? finish, AnimationRoute? route, double progress) { _start = start; _finish = finish; _route = route; _progress = progress; InvalidateVisual(); } public void SetProgress(double value) { _progress = Math.Clamp(value, 0, 1); InvalidateVisual(); }
        protected override void OnRender(DrawingContext dc) { if (_route is not null) DrawLine(dc, _route.Geometry, Brush("#EF4444"), 4); DrawMarker(dc, _start, Brush("#22C55E"), Brush("#14532D")); DrawMarker(dc, _finish, Brush("#EF4444"), Brush("#7F1D1D")); DrawVehicle(dc); }
        private void DrawLine(DrawingContext dc, IReadOnlyList<RoutePoint> points, Brush brush, double width) { if (points.Count < 2) return; var geometry = new StreamGeometry(); using (var c = geometry.Open()) { c.BeginFigure(Screen(points[0]), false, false); c.PolyLineTo(points.Skip(1).Select(Screen).ToArray(), true, true); } dc.DrawGeometry(null, new Pen(brush, width) { StartLineCap = PenLineCap.Round, EndLineCap = PenLineCap.Round, LineJoin = PenLineJoin.Round }, geometry); } private void DrawMarker(DrawingContext dc, RoutePoint? point, Brush fill, Brush outline) { if (point.HasValue) dc.DrawEllipse(fill, new Pen(outline, 2), Screen(point.Value), 8, 8); }
        private void DrawVehicle(DrawingContext dc) { if (_route is null || _progress < 0 || _route.Geometry.Count < 2) return; var lengths = _route.Geometry.Zip(_route.Geometry.Skip(1), (a, b) => Math.Sqrt(Math.Pow(b.X - a.X, 2) + Math.Pow(b.Y - a.Y, 2))).ToArray(); var total = lengths.Sum(); if (total <= 0) return; var target = total * _progress; var traversed = 0d; var position = _route.Geometry[0]; var direction = _route.Geometry[1]; for (var i = 1; i < _route.Geometry.Count; i++) { var length = lengths[i - 1]; if (target <= traversed + length || i == _route.Geometry.Count - 1) { var ratio = length > 0 ? Math.Clamp((target - traversed) / length, 0, 1) : 0; var a = _route.Geometry[i - 1]; var b = _route.Geometry[i]; position = new(a.X + (b.X - a.X) * ratio, a.Y + (b.Y - a.Y) * ratio); direction = b; break; } traversed += length; } var p = Screen(position); var d = Screen(direction); var angle = Math.Atan2(d.Y - p.Y, d.X - p.X); dc.DrawEllipse(Brush("#2563EB"), new Pen(Brush("#1E3A8A"), 2), p, 10, 10); dc.DrawLine(new Pen(Brush("#FFFFFF"), 3) { StartLineCap = PenLineCap.Round, EndLineCap = PenLineCap.Round }, p, new Point(p.X + Math.Cos(angle) * 7, p.Y + Math.Sin(angle) * 7)); } private Point Screen(RoutePoint p) { var v = _viewer.WorldToScreen(p.X, p.Y); return new(v.X, v.Y); }
    }
}
