namespace GeoKernel.RouteAnimation.Winforms;
internal readonly record struct RoutePoint(double X, double Y);
internal sealed record RouteNode(int Id, RoutePoint Position);
internal sealed record RouteEdge(int Id, int FromId, int ToId, double Distance, double SpeedKmh, IReadOnlyList<RoutePoint> Geometry, string Name);
internal sealed record AnimationRoute(IReadOnlyList<int> EdgeIds, IReadOnlyList<RoutePoint> Geometry, double Distance, double Time);
internal sealed class AnimationRoutingEngine
{
    private const double EarthRadius = 6371008.8, MercatorLimit = 20037508.342789244; private readonly Dictionary<int, RouteNode> _nodes; private readonly Dictionary<int, RouteEdge> _edges; private readonly Dictionary<int, List<RouteEdge>> _out;
    public AnimationRoutingEngine(IEnumerable<RouteNode> nodes, IEnumerable<RouteEdge> edges) { _nodes = nodes.ToDictionary(x => x.Id); _edges = edges.ToDictionary(x => x.Id); _out = _edges.Values.GroupBy(x => x.FromId).ToDictionary(x => x.Key, x => x.ToList()); }
    public IReadOnlySet<int> LargestComponent() { var visited = new HashSet<int>(); var largest = new HashSet<int>(); foreach (var seed in _nodes.Keys) { if (!visited.Add(seed)) continue; var set = new HashSet<int> { seed }; var q = new Queue<int>(); q.Enqueue(seed); while (q.Count > 0) foreach (var edge in _out.GetValueOrDefault(q.Dequeue()) ?? []) if (visited.Add(edge.ToId)) { set.Add(edge.ToId); q.Enqueue(edge.ToId); } if (set.Count > largest.Count) largest = set; } return largest; }
    public IReadOnlySet<int> Reachable(int start) { var set = new HashSet<int> { start }; var q = new Queue<int>(); q.Enqueue(start); while (q.Count > 0) foreach (var edge in _out.GetValueOrDefault(q.Dequeue()) ?? []) if (set.Add(edge.ToId)) q.Enqueue(edge.ToId); return set; }
    public RouteNode? Nearest(IReadOnlySet<int> candidates, RoutePoint point, double maximum) { RouteNode? result = null; var best = maximum; foreach (var id in candidates) if (_nodes.TryGetValue(id, out var node)) { var d = Distance(point, node.Position); if (d < best) { best = d; result = node; } } return result; }
    public AnimationRoute? FindRoute(int start, int finish) { var costs = new Dictionary<int, double> { [start] = 0 }; var previous = new Dictionary<int, RouteEdge>(); var q = new PriorityQueue<int, double>(); q.Enqueue(start, 0); while (q.TryDequeue(out var node, out var cost)) { if (cost > costs.GetValueOrDefault(node, double.PositiveInfinity)) continue; if (node == finish) break; foreach (var edge in _out.GetValueOrDefault(node) ?? []) { var candidate = cost + edge.Distance; if (candidate >= costs.GetValueOrDefault(edge.ToId, double.PositiveInfinity)) continue; costs[edge.ToId] = candidate; previous[edge.ToId] = edge; q.Enqueue(edge.ToId, candidate); } } if (!costs.ContainsKey(finish)) return null; var ids = new List<int>(); for (var node = finish; node != start;) { if (!previous.TryGetValue(node, out var edge)) return null; ids.Add(edge.Id); node = edge.FromId; } ids.Reverse(); var geometry = new List<RoutePoint>(); double distance = 0, time = 0; foreach (var id in ids) { var edge = _edges[id]; distance += edge.Distance; if (edge.SpeedKmh > 0) time += edge.Distance / (edge.SpeedKmh * 1000 / 3600); foreach (var point in edge.Geometry.Select(ToWebMercator)) if (geometry.Count == 0 || geometry[^1] != point) geometry.Add(point); } return geometry.Count > 1 ? new AnimationRoute(ids, geometry, distance, time) : null; }
    public IReadOnlyList<(string Name, double Distance)> Steps(AnimationRoute route) { var result = new List<(string, double)>(); foreach (var edge in route.EdgeIds.Select(id => _edges[id])) { var name = string.IsNullOrWhiteSpace(edge.Name) ? "Unnamed road" : edge.Name.Trim(); if (result.Count > 0 && string.Equals(result[^1].Item1, name, StringComparison.OrdinalIgnoreCase)) result[^1] = (result[^1].Item1, result[^1].Item2 + edge.Distance); else result.Add((name, edge.Distance)); } return result; }
    public static RoutePoint ToWgs84(RoutePoint p) => new(p.X / MercatorLimit * 180, Math.Atan(Math.Exp(p.Y / MercatorLimit * Math.PI)) * 360 / Math.PI - 90);
    public static RoutePoint ToWebMercator(RoutePoint p) { var latitude = Math.Clamp(p.Y, -85.05112878, 85.05112878); return new(p.X * MercatorLimit / 180, Math.Log(Math.Tan((90 + latitude) * Math.PI / 360)) * MercatorLimit / Math.PI); }
    private static double Distance(RoutePoint a, RoutePoint b) { var lat1 = a.Y * Math.PI / 180; var lat2 = b.Y * Math.PI / 180; var dlat = lat2 - lat1; var dlon = (b.X - a.X) * Math.PI / 180; var v = Math.Pow(Math.Sin(dlat / 2), 2) + Math.Cos(lat1) * Math.Cos(lat2) * Math.Pow(Math.Sin(dlon / 2), 2); return EarthRadius * 2 * Math.Atan2(Math.Sqrt(v), Math.Sqrt(1 - v)); }
}
