using System.Drawing.Drawing2D;
using GeoKernel.Examples.Common;
using GeoKernel.NET.WinForms;

namespace GeoKernel.RouteAnimation.Winforms;
public sealed class MainForm : Form
{
    private readonly GeoKernelViewerControl _viewer = new() { Dock = DockStyle.Fill }; private readonly ListBox _directions = new() { Dock = DockStyle.Fill }; private readonly Label _summary = new() { Text = "Select a start and finish point.", Dock = DockStyle.Fill }, _animationStatus = new() { Text = "Animation is waiting for a route.", Dock = DockStyle.Fill };
    private readonly Button _select = new() { Text = "Select route points", AutoSize = true, Enabled = false }, _play = new() { Text = "Play", Enabled = false }, _pause = new() { Text = "Pause", Enabled = false }, _resetAnimation = new() { Text = "Reset", Enabled = false }; private readonly ToolStripStatusLabel _status = new(); private readonly System.Windows.Forms.Timer _timer = new() { Interval = 33 }; private readonly Overlay _overlay;
    private AnimationRoutingEngine? _engine; private IReadOnlySet<int> _mainComponent = new HashSet<int>(); private RoutePoint? _start, _finish; private int _startNode = -1; private AnimationRoute? _route; private double _progress, _duration = 5000;
    public MainForm()
    {
        Text = "RouteAnimation"; Width = 1200; Height = 760; StartPosition = FormStartPosition.CenterScreen; var icon = Path.Combine(AppContext.BaseDirectory, "resources", "GeoKernelAppIcon.ico"); if (File.Exists(icon)) Icon = new Icon(icon);
        var toolbar = new FlowLayoutPanel { Dock = DockStyle.Top, Height = 34, WrapContents = false }; toolbar.Controls.Add(_select); AddLegend(toolbar, "Start", Color.FromArgb(34, 197, 94)); AddLegend(toolbar, "Finish", Color.FromArgb(239, 68, 68));
        var panel = new TableLayoutPanel { Dock = DockStyle.Right, Width = 300, Padding = new Padding(10), RowCount = 6 }; panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 22)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 50)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 55)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 36)); panel.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 0)); panel.Controls.Add(new Label { Text = "Route directions", Font = new Font(Font, FontStyle.Bold), Dock = DockStyle.Fill }, 0, 0); panel.Controls.Add(_summary, 0, 1); panel.Controls.Add(_animationStatus, 0, 2); var buttons = new FlowLayoutPanel { Dock = DockStyle.Fill }; buttons.Controls.AddRange([_play, _pause, _resetAnimation]); panel.Controls.Add(buttons, 0, 3); panel.Controls.Add(_directions, 0, 4);
        var bar = new StatusStrip(); bar.Items.Add(_status); Controls.Add(_viewer); Controls.Add(panel); Controls.Add(toolbar); Controls.Add(bar); _overlay = new Overlay(_viewer);
        Shown += LoadSample; Move += (_, _) => _overlay.SyncBounds(); Resize += (_, _) => _overlay.SyncBounds(); FormClosed += (_, _) => _overlay.Close(); _viewer.VisibleExtentChanged += (_, _) => _overlay.Invalidate(); _viewer.MapMouseUp += MapClicked; _select.Click += (_, _) => BeginSelection(); _play.Click += (_, _) => Play(); _pause.Click += (_, _) => Pause(); _resetAnimation.Click += (_, _) => ResetAnimation(); _timer.Tick += (_, _) => TickAnimation();
    }
    private static void AddLegend(Control p, string text, Color color) { p.Controls.Add(new Label { Text = "●", ForeColor = color, AutoSize = true, Padding = new Padding(8, 7, 0, 0) }); p.Controls.Add(new Label { Text = text, AutoSize = true, Padding = new Padding(0, 7, 0, 0) }); }
    private async void LoadSample(object? sender, EventArgs e)
    {
        UseWaitCursor = true; _status.Text = "Loading Stockholm road network..."; await Task.Yield();
        try { _viewer.ActiveTool = GeoKernelViewerTool.Pan; var path = SampleData.EnsureSampleFile(new Uri("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm.zip"), "stockholm.zip", "stockholm", "stockholm.shp", this); if (string.IsNullOrEmpty(path) || !_viewer.AddLayerFile(path)) return; _viewer.SetLayerCoordinateSystemPreset(0, GeoKernelCoordinateSystemPreset.Wgs84); _viewer.SetCoordinateSystemPreset(GeoKernelCoordinateSystemPreset.WebMercator); _viewer.SetLayerStyle(0, new GeoKernelLayerStyle { LineColor = "#718684", LineWidth = 1 }); if (!_viewer.BuildRoutingGraphForLayer(0, 1e-6, true, "maxspeed", "name", "oneway", 50)) throw new InvalidOperationException("Routing graph could not be built."); _status.Text = "Preparing routing graph..."; var snapshot = await Task.Run(() => _viewer.GetRoutingGraphSnapshot()) ?? throw new InvalidOperationException("Routing graph is unavailable."); var prepared = await Task.Run(() => { var engine = new AnimationRoutingEngine(snapshot.Nodes.Select(x => new RouteNode(x.Id, new(x.Position.X, x.Position.Y))), snapshot.Edges.Select(x => new RouteEdge(x.Id, x.FromId, x.ToId, x.Distance, x.SpeedKmh, x.Geometry.Select(p => new RoutePoint(p.X, p.Y)).ToArray(), x.Attributes.TryGetValue("name", out var name) ? name?.ToString() ?? "" : ""))); return (engine, engine.LargestComponent()); }); _engine = prepared.engine; _mainComponent = prepared.Item2; if (_mainComponent.Count == 0) throw new InvalidOperationException("The main connected road network could not be identified."); var extent = _viewer.GetLayerInfo(0)?.ProjectedExtent; if (extent is not null) _viewer.ViewExtent = extent.Value; _select.Enabled = true; _overlay.Show(this); BeginSelection(); }
        catch (Exception ex) { MessageBox.Show(this, ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Error); } finally { UseWaitCursor = false; }
    }
    private void DisableAnimation() { _timer.Stop(); _progress = 0; _play.Enabled = _pause.Enabled = _resetAnimation.Enabled = false; _animationStatus.Text = "Animation is waiting for a route."; }
    private void BeginSelection() { DisableAnimation(); _start = _finish = null; _startNode = -1; _route = null; _directions.Items.Clear(); _summary.Text = "Select a start and finish point."; _overlay.SetState(null, null, null, -1); _viewer.ActiveTool = GeoKernelViewerTool.Route; _status.Text = "Click the map to choose the start point."; }
    private void MapClicked(object? sender, GeoKernelMapMouseEventArgs e)
    {
        if (_engine is null || e.Tool != GeoKernelViewerTool.Route || (e.ButtonOrButtons & 1) == 0) return; var candidates = _start.HasValue && !_finish.HasValue ? _engine.Reachable(_startNode) : _mainComponent; var node = _engine.Nearest(candidates, AnimationRoutingEngine.ToWgs84(new(e.WorldPoint.X, e.WorldPoint.Y)), 2000); if (node is null) { MessageBox.Show(this, "No road node was found near the selected point.", Text, MessageBoxButtons.OK, MessageBoxIcon.Warning); return; } var world = AnimationRoutingEngine.ToWebMercator(node.Position);
        if (!_start.HasValue || _finish.HasValue) { DisableAnimation(); _start = world; _finish = null; _startNode = node.Id; _route = null; _directions.Items.Clear(); _summary.Text = "Select the finish point."; _overlay.SetState(_start, null, null, -1); _status.Text = "Start selected. Click the map to choose the finish point."; return; }
        _finish = world; _route = _engine.FindRoute(_startNode, node.Id); if (_route is null) { _overlay.SetState(_start, _finish, null, -1); MessageBox.Show(this, "No connected route was found.", Text, MessageBoxButtons.OK, MessageBoxIcon.Warning); _status.Text = "No connected route found. Click once to choose a new start."; return; } _progress = 0; _duration = Math.Clamp(_route.Time / 60 * 1000, 5000, 45000); _overlay.SetState(_start, _finish, _route, 0); _play.Enabled = _resetAnimation.Enabled = true; _pause.Enabled = false; _animationStatus.Text = $"Ready: {_route.Distance / 1000:0.00} km • {_route.Time / 60:0.0} min\r\nAnimation speed adapts to route length."; _summary.Text = $"{_route.Distance / 1000:0.00} km  •  {_route.Time / 60:0.0} min"; _directions.Items.Clear(); var steps = _engine.Steps(_route); for (var i = 0; i < steps.Count; i++) _directions.Items.Add($"{i + 1}. {steps[i].Name}\r\n    {(steps[i].Distance >= 1000 ? $"{steps[i].Distance / 1000:0.0} km" : $"{steps[i].Distance:0} m")}"); if (steps.Count == 0) _directions.Items.Add("Route has no named road segments."); _status.Text = $"Route: {_route.Distance / 1000:0.00} km, {_route.Time / 60:0.0} min";
    }
    private void Play() { if (_route is null) return; if (_progress >= 1) { _progress = 0; _overlay.SetProgress(0); } _timer.Start(); _play.Enabled = false; _pause.Enabled = true; }
    private void Pause() { _timer.Stop(); _play.Enabled = true; _pause.Enabled = false; }
    private void ResetAnimation() { if (_route is null) return; _timer.Stop(); _progress = 0; _overlay.SetProgress(0); _animationStatus.Text = $"Ready: {_route.Distance / 1000:0.00} km • {_route.Time / 60:0.0} min"; _play.Enabled = true; _pause.Enabled = false; }
    private void TickAnimation() { if (_route is null) return; _progress = Math.Min(1, _progress + _timer.Interval / _duration); _overlay.SetProgress(_progress); _animationStatus.Text = $"Progress: {_progress * 100:0}%\r\nRemaining: {_route.Distance * (1 - _progress) / 1000:0.00} km • {_route.Time * (1 - _progress) / 60:0.0} min"; if (_progress >= 1) { _timer.Stop(); _pause.Enabled = false; _animationStatus.Text = "Destination reached."; } }
    private sealed class Overlay : Form
    {
        private readonly GeoKernelViewerControl _viewer; private RoutePoint? _start, _finish; private AnimationRoute? _route; private double _progress = -1;
        public Overlay(GeoKernelViewerControl viewer) { _viewer = viewer; FormBorderStyle = FormBorderStyle.None; ShowInTaskbar = false; BackColor = Color.Fuchsia; TransparencyKey = Color.Fuchsia; StartPosition = FormStartPosition.Manual; } protected override bool ShowWithoutActivation => true; protected override CreateParams CreateParams { get { var p = base.CreateParams; p.ExStyle |= 0x08000020 | 0x80; return p; } } public void SyncBounds() { if (!Visible || !_viewer.IsHandleCreated) return; Bounds = new Rectangle(_viewer.PointToScreen(Point.Empty), _viewer.ClientSize); Invalidate(); } public void SetState(RoutePoint? start, RoutePoint? finish, AnimationRoute? route, double progress) { _start = start; _finish = finish; _route = route; _progress = progress; SyncBounds(); } public void SetProgress(double value) { _progress = Math.Clamp(value, 0, 1); Invalidate(); } protected override void OnShown(EventArgs e) { base.OnShown(e); SyncBounds(); }
        protected override void OnPaint(PaintEventArgs e) { e.Graphics.SmoothingMode = SmoothingMode.AntiAlias; if (_route is not null) DrawLine(e.Graphics, _route.Geometry, Color.FromArgb(239, 68, 68), 4); DrawMarker(e.Graphics, _start, Color.FromArgb(34, 197, 94), Color.FromArgb(20, 83, 45)); DrawMarker(e.Graphics, _finish, Color.FromArgb(239, 68, 68), Color.FromArgb(127, 29, 29)); DrawVehicle(e.Graphics); }
        private void DrawLine(Graphics g, IReadOnlyList<RoutePoint> points, Color color, float width) { if (points.Count < 2) return; using var pen = new Pen(color, width) { StartCap = LineCap.Round, EndCap = LineCap.Round, LineJoin = LineJoin.Round }; g.DrawLines(pen, points.Select(Screen).ToArray()); } private void DrawMarker(Graphics g, RoutePoint? point, Color fill, Color outline) { if (!point.HasValue) return; var p = Screen(point.Value); using var b = new SolidBrush(fill); using var pen = new Pen(outline, 2); g.FillEllipse(b, p.X - 8, p.Y - 8, 16, 16); g.DrawEllipse(pen, p.X - 8, p.Y - 8, 16, 16); }
        private void DrawVehicle(Graphics g) { if (_route is null || _progress < 0 || _route.Geometry.Count < 2) return; var lengths = _route.Geometry.Zip(_route.Geometry.Skip(1), (a, b) => Math.Sqrt(Math.Pow(b.X - a.X, 2) + Math.Pow(b.Y - a.Y, 2))).ToArray(); var total = lengths.Sum(); if (total <= 0) return; var target = total * _progress; var traversed = 0d; var position = _route.Geometry[0]; var direction = _route.Geometry[1]; for (var i = 1; i < _route.Geometry.Count; i++) { var length = lengths[i - 1]; if (target <= traversed + length || i == _route.Geometry.Count - 1) { var ratio = length > 0 ? Math.Clamp((target - traversed) / length, 0, 1) : 0; var a = _route.Geometry[i - 1]; var b = _route.Geometry[i]; position = new(a.X + (b.X - a.X) * ratio, a.Y + (b.Y - a.Y) * ratio); direction = b; break; } traversed += length; } var p = Screen(position); var d = Screen(direction); var angle = Math.Atan2(d.Y - p.Y, d.X - p.X); using var bsh = new SolidBrush(Color.FromArgb(37, 99, 235)); using var outline = new Pen(Color.FromArgb(30, 58, 138), 2); g.FillEllipse(bsh, p.X - 10, p.Y - 10, 20, 20); g.DrawEllipse(outline, p.X - 10, p.Y - 10, 20, 20); using var arrow = new Pen(Color.White, 3) { StartCap = LineCap.Round, EndCap = LineCap.Round }; g.DrawLine(arrow, p, new PointF(p.X + (float)Math.Cos(angle) * 7, p.Y + (float)Math.Sin(angle) * 7)); }
        private PointF Screen(RoutePoint p) { var v = _viewer.WorldToScreen(p.X, p.Y); return new((float)v.X, (float)v.Y); }
    }
}
