<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <ApplicationIcon>..\Project.Winforms\resources\geokernel.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GeoKernel.NET" Version="1.1.28" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\Project.Winforms\resources\ZoomIn.png" Link="Images\ZoomIn.png" />
    <Resource Include="..\Project.Winforms\resources\ZoomOut.png" Link="Images\ZoomOut.png" />
    <Resource Include="..\Project.Winforms\resources\FullExtent.png" Link="Images\FullExtent.png" />
    <Resource Include="..\Project.Winforms\resources\RectangularZoom.png" Link="Images\RectangularZoom.png" />
    <Resource Include="..\Project.Winforms\resources\Pan.png" Link="Images\Pan.png" />
    <Resource Include="..\Project.Winforms\resources\geokernel.ico" Link="Images\GeoKernelAppIcon.ico" />
  </ItemGroup>
  <ItemGroup><ProjectReference Include="..\Common\Common.csproj" /></ItemGroup>
</Project>
