using System.Drawing.Drawing2D;
using GeoKernel.Examples.Common;
using GeoKernel.NET.WinForms;

namespace GeoKernel.Isochrone.Winforms;
public sealed class MainForm : Form
{
    private readonly GeoKernelViewerControl _viewer = new() { Dock = DockStyle.Fill }; private readonly Button _select = new() { Text = "Select isochrone origin", AutoSize = true, Enabled = false }; private readonly Label _summary = new() { Text = "Select an origin point.", Dock = DockStyle.Fill }; private readonly ListBox _bands = new() { Dock = DockStyle.Fill }; private readonly ToolStripStatusLabel _status = new(); private readonly Overlay _overlay; private IsochroneEngine? _engine; private IReadOnlySet<int> _component = new HashSet<int>(); private RoutePoint? _origin; private IsochroneResult? _result; private bool _calculating;
    public MainForm()
    {
        Text = "Isochrone"; Width = 1200; Height = 760; StartPosition = FormStartPosition.CenterScreen; var icon = Path.Combine(AppContext.BaseDirectory, "resources", "GeoKernelAppIcon.ico"); if (File.Exists(icon)) Icon = new Icon(icon);
        var toolbar = new FlowLayoutPanel { Dock = DockStyle.Top, Height = 34, WrapContents = false }; toolbar.Controls.Add(_select); toolbar.Controls.Add(new Label { Text = "●", ForeColor = Color.FromArgb(34, 197, 94), AutoSize = true, Padding = new Padding(8, 7, 0, 0) }); toolbar.Controls.Add(new Label { Text = "Origin", AutoSize = true, Padding = new Padding(0, 7, 0, 0) });
        var panel = new TableLayoutPanel { Dock = DockStyle.Right, Width = 310, Padding = new Padding(10), RowCount = 4 }; panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 24)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 56)); panel.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); panel.RowStyles.Add(new RowStyle(SizeType.Absolute, 110)); panel.Controls.Add(new Label { Text = "Travel-time isochrone", Font = new Font(Font, FontStyle.Bold), Dock = DockStyle.Fill }, 0, 0); panel.Controls.Add(_summary, 0, 1); panel.Controls.Add(_bands, 0, 2); panel.Controls.Add(new Label { Text = "Click a band to highlight it.\r\n\r\nGreen: 0–5 min\r\nOrange: 5–10 min\r\nRed: 10–15 min", Dock = DockStyle.Fill }, 0, 3);
        var bar = new StatusStrip(); bar.Items.Add(_status); Controls.Add(_viewer); Controls.Add(panel); Controls.Add(toolbar); Controls.Add(bar); _overlay = new Overlay(_viewer); Shown += LoadSample; Move += (_, _) => _overlay.SyncBounds(); Resize += (_, _) => _overlay.SyncBounds(); FormClosed += (_, _) => _overlay.Close(); _viewer.VisibleExtentChanged += (_, _) => _overlay.Redraw(); _viewer.MapMouseUp += MapClicked; _select.Click += (_, _) => BeginSelection(); _bands.SelectedIndexChanged += (_, _) => { if (_bands.SelectedIndex >= 0) _overlay.SetState(_origin, _result, _bands.SelectedIndex); };
    }
    private async void LoadSample(object? sender, EventArgs e) { UseWaitCursor = true; _status.Text = "Loading Stockholm road network..."; await Task.Yield(); try { _viewer.ActiveTool = GeoKernelViewerTool.Pan; var path = SampleData.EnsureSampleFile(new Uri("https://github.com/geokernel-io/GeoKernel.SampleData/releases/download/v1/stockholm.zip"), "stockholm.zip", "stockholm", "stockholm.shp", this); if (string.IsNullOrEmpty(path) || !_viewer.AddLayerFile(path)) return; _viewer.SetLayerCoordinateSystemPreset(0, GeoKernelCoordinateSystemPreset.Wgs84); _viewer.SetCoordinateSystemPreset(GeoKernelCoordinateSystemPreset.WebMercator); _viewer.SetLayerStyle(0, new GeoKernelLayerStyle { LineColor = "#718684", LineWidth = 1 }); if (!_viewer.BuildRoutingGraphForLayer(0, 1e-6, true, "maxspeed", "name", "oneway", 50)) throw new InvalidOperationException("Routing graph could not be built."); _status.Text = "Preparing routing graph..."; var snapshot = await Task.Run(() => _viewer.GetRoutingGraphSnapshot()) ?? throw new InvalidOperationException("Routing graph is unavailable."); var prepared = await Task.Run(() => { var engine = new IsochroneEngine(snapshot.Nodes.Select(x => new RouteNode(x.Id, new(x.Position.X, x.Position.Y))), snapshot.Edges.Select(x => new RouteEdge(x.Id, x.FromId, x.ToId, x.Distance, x.SpeedKmh, x.Geometry.Select(p => new RoutePoint(p.X, p.Y)).ToArray()))); return (engine, engine.LargestComponent()); }); _engine = prepared.engine; _component = prepared.Item2; var extent = _viewer.GetLayerInfo(0)?.ProjectedExtent; if (extent is not null) _viewer.ViewExtent = extent.Value; _select.Enabled = true; _overlay.Show(this); BeginSelection(); } catch (Exception ex) { MessageBox.Show(this, ex.Message, Text, MessageBoxButtons.OK, MessageBoxIcon.Error); } finally { UseWaitCursor = false; } }
    private void BeginSelection() { _origin = null; _result = null; _bands.Items.Clear(); _summary.Text = "Select an origin point."; _overlay.SetState(null, null, -1); _viewer.ActiveTool = GeoKernelViewerTool.Route; _status.Text = "Click the map to choose an isochrone origin."; }
    private async void MapClicked(object? sender, GeoKernelMapMouseEventArgs e) { if (_calculating || _engine is null || e.Tool != GeoKernelViewerTool.Route || (e.ButtonOrButtons & 1) == 0) return; var snap = _engine.Nearest(_component, IsochroneEngine.ToWgs84(new(e.WorldPoint.X, e.WorldPoint.Y)), 2000); if (snap is null) { MessageBox.Show(this, "No road node was found near the selected point.", Text, MessageBoxButtons.OK, MessageBoxIcon.Warning); return; } _calculating = true; _select.Enabled = false; _status.Text = "Calculating isochrone..."; _origin = IsochroneEngine.ToWebMercator(snap.Node.Position); _overlay.SetState(_origin, null, -1); try { _result = await Task.Run(() => _engine.Calculate(snap.Node.Id)); _bands.Items.Clear(); var minutes = new[] { 5, 10, 15 }; for (var i = 0; i < 3; i++) _bands.Items.Add($"Within {minutes[i]} minutes\r\n{_result.Bands[i].CumulativeNodes} cumulative nodes • {_result.Bands[i].EdgeCount} band edges"); _summary.Text = $"Origin snap: {snap.Distance:0.0} m\r\n{_result.Bands[2].CumulativeNodes} nodes reachable within 15 minutes."; _bands.SelectedIndex = 0; _overlay.SetState(_origin, _result, 0); _status.Text = "Isochrone calculated successfully."; } finally { _calculating = false; _select.Enabled = true; } }
    private sealed class Overlay : Form { private readonly GeoKernelViewerControl _viewer; private readonly GraphicsPath?[] _paths = new GraphicsPath?[3]; private RoutePoint? _origin; private IsochroneResult? _result; private int _active; private static readonly Color[] Colors = [Color.FromArgb(22,163,74), Color.FromArgb(245,158,11), Color.FromArgb(220,38,38)]; public Overlay(GeoKernelViewerControl viewer) { _viewer = viewer; FormBorderStyle = FormBorderStyle.None; ShowInTaskbar = false; BackColor = Color.Fuchsia; TransparencyKey = Color.Fuchsia; StartPosition = FormStartPosition.Manual; } protected override bool ShowWithoutActivation => true; protected override CreateParams CreateParams { get { var p = base.CreateParams; p.ExStyle |= 0x08000020 | 0x80; return p; } } public void SyncBounds() { if (!Visible || !_viewer.IsHandleCreated) return; Bounds = new Rectangle(_viewer.PointToScreen(Point.Empty), _viewer.ClientSize); Redraw(); } public void Redraw() { for (var i=0;i<_paths.Length;i++) { _paths[i]?.Dispose(); _paths[i]=null; } Invalidate(); } public void SetState(RoutePoint? origin, IsochroneResult? result, int active) { var changed=!ReferenceEquals(_result,result); _origin = origin; _result = result; _active = active; if(changed) Redraw(); else Invalidate(); } protected override void OnShown(EventArgs e) { base.OnShown(e); SyncBounds(); } protected override void OnPaint(PaintEventArgs e) { e.Graphics.SmoothingMode = SmoothingMode.AntiAlias; if (_result is not null) for (var band = 2; band >= 0; band--) { using var pen = new Pen(Color.FromArgb(band == _active ? 250 : 135, Colors[band]), band == _active ? 4.5f : 2.5f) { StartCap = LineCap.Round, EndCap = LineCap.Round, LineJoin = LineJoin.Round }; e.Graphics.DrawPath(pen,PathFor(band)); } if (_origin is { } o) { var p = Screen(o); using var b = new SolidBrush(Color.FromArgb(34,197,94)); using var pen = new Pen(Color.FromArgb(20,83,45), 2); e.Graphics.FillEllipse(b,p.X-9,p.Y-9,18,18); e.Graphics.DrawEllipse(pen,p.X-9,p.Y-9,18,18); } } private GraphicsPath PathFor(int band) { if(_paths[band] is not null)return _paths[band]!; var path=new GraphicsPath(); if(_result is not null) foreach(var line in _result.Bands[band].Lines) { var points=line.Select(Screen).Where(p=>float.IsFinite(p.X)&&float.IsFinite(p.Y)).ToArray(); if(points.Length>1){path.StartFigure();path.AddLines(points);} } return _paths[band]=path; } private PointF Screen(RoutePoint p) { var v = _viewer.WorldToScreen(p.X,p.Y); return new((float)v.X,(float)v.Y); } }
}
