using System.Text.Json;
using GeoKernel.NET.WinForms;
namespace GeoKernel.RasterTileCache.Winforms;
public sealed partial class MainForm : Form
{
    private string _rasterPath="", _mode="No Raster Loaded"; private JsonElement? _benchmark;
    public MainForm()=>InitializeComponent();
    private async void MainForm_Shown(object? s,EventArgs e){viewerControl.ActiveTool=GeoKernelViewerTool.Pan;statusLabel.Text="Preparing sample data...";_rasterPath=await SampleData.EnsureFileAsync("world_8km_tif.zip","world_8km_tif","world_8km.tif","World GeoTIFF",this);if(!string.IsNullOrWhiteSpace(_rasterPath))LoadRaster(CacheMode.Large);}
    private void loadDisabledButton_Click(object? s,EventArgs e)=>LoadRaster(CacheMode.Disabled); private void loadSmallButton_Click(object? s,EventArgs e)=>LoadRaster(CacheMode.Small); private void loadLargeButton_Click(object? s,EventArgs e)=>LoadRaster(CacheMode.Large); private void fullExtentButton_Click(object? s,EventArgs e)=>viewerControl.FullExtent(); private void benchmarkButton_Click(object? s,EventArgs e)=>ReadDiagnostics(true,false); private void clearCacheButton_Click(object? s,EventArgs e){ReadDiagnostics(false,true);_benchmark=null;statusLabel.Text="Memory tile cache cleared.";}
    private void LoadRaster(CacheMode mode)
    {try{viewerControl.ClearLayers();progressBar.Value=0;_benchmark=null;_mode=ModeText(mode);statusLabel.Text=$"Loading {_mode}...";var o=new GeoKernelLayerLoadOptions{PrepareRasterOverviews=true,RasterOverviewMinimumPixels=0,RasterTileCacheEnabled=mode!=CacheMode.Disabled};if(mode==CacheMode.Small){o.RasterTileCachePixelBudget=128*1024;o.RasterTileCacheMaximumItemPixels=128*1024;}else if(mode==CacheMode.Large){o.RasterTileCachePixelBudget=4*1024*1024;o.RasterTileCacheMaximumItemPixels=512*512;}else{o.RasterTileCachePixelBudget=0;o.RasterTileCacheMaximumItemPixels=0;}var p=new Progress<GeoKernelLayerLoadProgress>(x=>{if(x.Progress.HasValue)progressBar.Value=Math.Clamp(x.Progress.Value,0,100);if(!string.IsNullOrWhiteSpace(x.Status))statusLabel.Text=x.Status;});if(!viewerControl.AddLayerFile(_rasterPath,o,p))throw new InvalidOperationException($"Raster could not be loaded:\n{_rasterPath}");viewerControl.SetLayerName(0,_mode);viewerControl.FullExtent();progressBar.Value=100;statusLabel.Text=$"{_mode} loaded.";ReadDiagnostics(false,false);}catch(Exception ex){statusLabel.Text="Load failed.";MessageBox.Show(this,ex.Message,Text,MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private void ReadDiagnostics(bool benchmark,bool clear)
    {if(viewerControl.LayerCount==0){statusLabel.Text="Load a raster first.";return;}try{if(benchmark)statusLabel.Text="Running tile cache benchmark...";var json=viewerControl.GetRasterTileCacheDiagnosticsJson(0,benchmark,clear);using var d=JsonDocument.Parse(json);var root=d.RootElement.Clone();if(root.TryGetProperty("benchmark",out var b))_benchmark=b.Clone();detailsTextBox.Text=Details(root);if(benchmark)statusLabel.Text=Summary(_benchmark);}catch(Exception ex){MessageBox.Show(this,ex.Message,Text,MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private string Details(JsonElement r){var l=new List<string>{"RasterTileCache sample","",$"Load mode: {_mode}",$"Source: {_rasterPath}","","Raster metadata",$"Driver: {G(r,"driverName")}",$"Size: {G(r,"width")} x {G(r,"height")} px",$"Bands: {G(r,"bandCount")}",$"Overview count: {G(r,"overviewCount")}","","Cache stats",$"Enabled: {G(r,"enabled")}",$"Items: {G(r,"itemCount")}",$"Used pixel cost: {G(r,"usedPixelCost")}",$"Max pixel cost: {G(r,"maxPixelCost")}",$"Max item pixel cost: {G(r,"maxItemPixelCost")}","","LayerLoadOptions knobs","RasterTileCacheEnabled","RasterTileCachePixelBudget","RasterTileCacheMaximumItemPixels","",BenchmarkText(_benchmark)};return string.Join(Environment.NewLine,l);}
    private static string BenchmarkText(JsonElement? b)=>b is not {ValueKind:JsonValueKind.Object}?"Benchmark has not run.":string.Join(Environment.NewLine,"Benchmark",$"Tiles read per pass: {G(b.Value,"tileCount")}",$"First pass: {G(b.Value,"firstPassMs")} ms, cache hits={G(b.Value,"firstPassHits")}, overview={G(b.Value,"firstPassOverviewLevel")}",$"Second pass: {G(b.Value,"secondPassMs")} ms, cache hits={G(b.Value,"secondPassHits")}, overview={G(b.Value,"secondPassOverviewLevel")}","","How to read this","- First pass fills the memory tile cache.","- Second pass requests the same tiles again.","- Large budget should retain all tiles; disabled cache should report zero hits.");
    private static string Summary(JsonElement? b)=>b is null?"Benchmark failed.":$"Second pass: {G(b.Value,"secondPassMs")} ms, cache hits={G(b.Value,"secondPassHits")}."; private static string G(JsonElement e,string n)=>e.TryGetProperty(n,out var v)?v.ToString():"-"; private static string ModeText(CacheMode m)=>m switch{CacheMode.Disabled=>"Cache Disabled",CacheMode.Small=>"Small Cache Budget",_=>"Large Cache Budget"}; private enum CacheMode{Disabled,Small,Large}
}
